<?
#/*====================================================================*/# 
#|화일명	: conf 파일 설정 변수명										|#
#|작성자	: 박영미													|#
#|작성일	: 2012.11.13												|#
#|작성내용	: conf 파일 설정 변수명										|#
#/*====================================================================*/#

$_CONF_FIELD_NAME["LAYOUT"]["DM_CODE"]				= "S_DESIGN_LAYOUT";
$_CONF_FIELD_NAME["INTRO"]["WEB_LOGO_TYPE"]			= "S_WEB_LOGO_TYPE";
$_CONF_FIELD_NAME["INTRO"]["WEB_LOGO_IMG"]			= "S_WEB_LOGO_IMG";
$_CONF_FIELD_NAME["INTRO"]["MOB_LOGO_IMG"]			= "S_MOB_LOGO_IMG";
$_CONF_FIELD_NAME["INTRO"]["DL_FIRST_USE"]			= "S_DESIGN_AUTO";
$_CONF_FIELD_NAME["INTRO"]["DL_BG_TYPE"]			= "S_DESIGN_TYPE";
$_CONF_FIELD_NAME["INTRO"]["DL_BG_COLOR"]			= "S_DESIGN_BG_COLOR";
$_CONF_FIELD_NAME["INTRO"]["DL_BG_IMAGE"]			= "S_DESIGN_BG_IMAGE";
$_CONF_FIELD_NAME["INTRO"]["DL_BG_IMG_DIR_H"]		= "S_DESIGN_BG_IMG_DIR_H";
$_CONF_FIELD_NAME["INTRO"]["DL_BG_IMAGE_OLD"]		= "S_DESIGN_BG_IMG_OLD";
$_CONF_FIELD_NAME["INTRO"]["DL_BG_IMG_DIR_V"]		= "S_DESIGN_BG_IMG_DIR_V";
$_CONF_FIELD_NAME["INTRO"]["DL_BG_REPEAT"]			= "S_DESIGN_BG_REPEAT";
$_CONF_FIELD_NAME["INTRO"]["DL_BG_ALIGN"]			= "S_DESIGN_ALIGN";
$_CONF_FIELD_NAME["INTRO"]["DL_FIRST_PAGE"]			= "S_DESIGN_INTRO";
$_CONF_FIELD_NAME["INTRO"]["DL_FIRST_USE"]			= "S_DESIGN_AUTO";
$_CONF_FIELD_NAME["INTRO"]["DL_BACKGROUND"]			= "S_DESIGN_BACKGROUND";

/* 메인 상품리스트 이미지(진열관리) 설정  */
// 사용유무 
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_PRODLIST_USE_LIST"]			= "S_MAIN_PRODLIST_USE";

/* 레이어 팝업 사용 유무 */
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_LAYERPOP_LOGIN_USE"]			= "S_MAIN_LAYERPOP_LOGIN_USE";	// 로그인 폼
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_LAYERPOP_JOIN_USE"]			= "S_MAIN_LAYERPOP_JOIN_USE";	// 회원가입 폼


// 메인 움직이는 이미지(배너)
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_SLIDER_USE"]					= "S_MAIN_SLIDER_USE";				// 사용유무
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_SLIDER_MOTION_USE"]			= "S_MAIN_SLIDER_MOTION_USE";		// 모션사용여부
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_SLIDER_MOTION_EFFECT"]			= "S_MAIN_SLIDER_MOTION_EFFECT";	// 모션효과
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_SLIDER_MOTION_TYPE"]			= "S_MAIN_SLIDER_MOTION_TYPE";		// 모션방법(좌에서우로:A,우에서좌로:B,위에서아래로:C,아래서위로:D,페이드인,페이드아웃:E)
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_SLIDER_IMAGE_SIZE_W"]			= "S_MAIN_SLIDER_IMAGE_SIZE_W";		// 이미지 가로사이즈
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_SLIDER_IMAGE_SIZE_H"]			= "S_MAIN_SLIDER_IMAGE_SIZE_H";		// 이미지 세로사이즈

// 사용자 정의 베스트 상품1
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_USE"]				= "S_ARY_MAIN_PRODLIST_USE[1]";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_NAME"]				= "S_MAIN_PRODLIST_TIT_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_DESIGN"]			= "S_MAIN_BEST_LIST1_DESIGN";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_SIZE_W"]			= "S_MAIN_PRODLIST_IMG_SIZE_W_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_SIZE_H"]			= "S_MAIN_PRODLIST_IMG_SIZE_H_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_VIEW_W"]			= "S_MAIN_PRODLIST_IMG_VIEW_W_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_VIEW_H"]			= "S_MAIN_PRODLIST_IMG_VIEW_H_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_SHOW_1"]			= "S_MAIN_BEST_LIST1_SHOW_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_SHOW_2"]			= "S_MAIN_BEST_LIST1_SHOW_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_SHOW_3"]			= "S_MAIN_BEST_LIST1_SHOW_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_SHOW_4"]			= "S_MAIN_BEST_LIST1_SHOW_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_SHOW_5"]			= "S_MAIN_BEST_LIST1_SHOW_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_SHOW_6"]			= "S_MAIN_BEST_LIST1_SHOW_6";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_SHOW_7"]			= "S_MAIN_BEST_LIST1_SHOW_7";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_SHOW_8"]			= "S_MAIN_BEST_LIST1_SHOW_8";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_COLOR_1"]			= "S_MAIN_BEST_LIST1_COLOR_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_COLOR_2"]			= "S_MAIN_BEST_LIST1_COLOR_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_COLOR_3"]			= "S_MAIN_BEST_LIST1_COLOR_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_COLOR_4"]			= "S_MAIN_BEST_LIST1_COLOR_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_COLOR_5"]			= "S_MAIN_BEST_LIST1_COLOR_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_COLOR_6"]			= "S_MAIN_BEST_LIST1_COLOR_6";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_COLOR_7"]			= "S_MAIN_BEST_LIST1_COLOR_7";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_COLOR_8"]			= "S_MAIN_BEST_LIST1_COLOR_8";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_WORD_ALIGN"]		= "S_MAIN_BEST_LIST1_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_MONEY_TYPE"]		= "S_MAIN_BEST_LIST1_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_MONEY_ICON"]		= "S_MAIN_BEST_LIST1_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_TURN_USE"]			= "S_MAIN_BEST_LIST1_TURN_USE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_TITLE_SHOW_USE"]	= "S_MAIN_BEST_LIST1_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_TITLE_FILE_NAME"]	= "S_MAIN_BEST_LIST1_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST1_TITLE_MAXSIZE"]		= "S_MAIN_BEST_LIST1_TITLE_MAXSIZE";
//$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_TOP_MENU"]					= "S_MAIN_TOP_MENU";

// 사용자 정의 베스트 상품2
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_USE"]				= "S_ARY_MAIN_PRODLIST_USE[2]";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_NAME"]				= "S_MAIN_PRODLIST_TIT_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_DESIGN"]			= "S_MAIN_BEST_LIST2_DESIGN";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_SIZE_W"]			= "S_MAIN_PRODLIST_IMG_SIZE_W_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_SIZE_H"]			= "S_MAIN_PRODLIST_IMG_SIZE_H_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_VIEW_W"]			= "S_MAIN_PRODLIST_IMG_VIEW_W_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_VIEW_H"]			= "S_MAIN_PRODLIST_IMG_VIEW_H_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_SHOW_1"]			= "S_MAIN_BEST_LIST2_SHOW_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_SHOW_2"]			= "S_MAIN_BEST_LIST2_SHOW_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_SHOW_3"]			= "S_MAIN_BEST_LIST2_SHOW_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_SHOW_4"]			= "S_MAIN_BEST_LIST2_SHOW_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_SHOW_5"]			= "S_MAIN_BEST_LIST2_SHOW_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_SHOW_6"]			= "S_MAIN_BEST_LIST2_SHOW_6";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_SHOW_7"]			= "S_MAIN_BEST_LIST2_SHOW_7";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_SHOW_8"]			= "S_MAIN_BEST_LIST2_SHOW_8";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_COLOR_1"]			= "S_MAIN_BEST_LIST2_COLOR_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_COLOR_2"]			= "S_MAIN_BEST_LIST2_COLOR_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_COLOR_3"]			= "S_MAIN_BEST_LIST2_COLOR_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_COLOR_4"]			= "S_MAIN_BEST_LIST2_COLOR_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_COLOR_5"]			= "S_MAIN_BEST_LIST2_COLOR_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_COLOR_6"]			= "S_MAIN_BEST_LIST2_COLOR_6";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_COLOR_7"]			= "S_MAIN_BEST_LIST2_COLOR_7";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_COLOR_8"]			= "S_MAIN_BEST_LIST2_COLOR_8";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_WORD_ALIGN"]		= "S_MAIN_BEST_LIST2_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_MONEY_TYPE"]		= "S_MAIN_BEST_LIST2_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_MONEY_ICON"]		= "S_MAIN_BEST_LIST2_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_TURN_USE"]			= "S_MAIN_BEST_LIST2_TURN_USE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_TITLE_SHOW_USE"]	= "S_MAIN_BEST_LIST2_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_TITLE_FILE_NAME"]	= "S_MAIN_BEST_LIST2_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST2_TITLE_MAXSIZE"]		= "S_MAIN_BEST_LIST2_TITLE_MAXSIZE";

// 사용자 정의 베스트 상품3
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_USE"]				= "S_ARY_MAIN_PRODLIST_USE[3]";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_NAME"]				= "S_MAIN_PRODLIST_TIT_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_DESIGN"]			= "S_MAIN_BEST_LIST3_DESIGN";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_SIZE_W"]			= "S_MAIN_PRODLIST_IMG_SIZE_W_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_SIZE_H"]			= "S_MAIN_PRODLIST_IMG_SIZE_H_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_VIEW_W"]			= "S_MAIN_PRODLIST_IMG_VIEW_W_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_VIEW_H"]			= "S_MAIN_PRODLIST_IMG_VIEW_H_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_SHOW_1"]			= "S_MAIN_BEST_LIST3_SHOW_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_SHOW_2"]			= "S_MAIN_BEST_LIST3_SHOW_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_SHOW_3"]			= "S_MAIN_BEST_LIST3_SHOW_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_SHOW_4"]			= "S_MAIN_BEST_LIST3_SHOW_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_SHOW_5"]			= "S_MAIN_BEST_LIST3_SHOW_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_SHOW_6"]			= "S_MAIN_BEST_LIST3_SHOW_6";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_SHOW_7"]			= "S_MAIN_BEST_LIST3_SHOW_7";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_SHOW_8"]			= "S_MAIN_BEST_LIST3_SHOW_8";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_COLOR_1"]			= "S_MAIN_BEST_LIST3_COLOR_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_COLOR_2"]			= "S_MAIN_BEST_LIST3_COLOR_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_COLOR_3"]			= "S_MAIN_BEST_LIST3_COLOR_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_COLOR_4"]			= "S_MAIN_BEST_LIST3_COLOR_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_COLOR_5"]			= "S_MAIN_BEST_LIST3_COLOR_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_COLOR_6"]			= "S_MAIN_BEST_LIST3_COLOR_6";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_COLOR_7"]			= "S_MAIN_BEST_LIST3_COLOR_7";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_COLOR_8"]			= "S_MAIN_BEST_LIST3_COLOR_8";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_WORD_ALIGN"]		= "S_MAIN_BEST_LIST3_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_MONEY_TYPE"]		= "S_MAIN_BEST_LIST3_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_MONEY_ICON"]		= "S_MAIN_BEST_LIST3_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_TURN_USE"]			= "S_MAIN_BEST_LIST3_TURN_USE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_TITLE_SHOW_USE"]	= "S_MAIN_BEST_LIST3_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_TITLE_FILE_NAME"]	= "S_MAIN_BEST_LIST3_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST3_TITLE_MAXSIZE"]		= "S_MAIN_BEST_LIST3_TITLE_MAXSIZE";

// 사용자 정의 베스트 상품4
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_USE"]				= "S_ARY_MAIN_PRODLIST_USE[4]";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_NAME"]				= "S_MAIN_PRODLIST_TIT_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_DESIGN"]			= "S_MAIN_BEST_LIST4_DESIGN";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_SIZE_W"]			= "S_MAIN_PRODLIST_IMG_SIZE_W_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_SIZE_H"]			= "S_MAIN_PRODLIST_IMG_SIZE_H_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_VIEW_W"]			= "S_MAIN_PRODLIST_IMG_VIEW_W_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_VIEW_H"]			= "S_MAIN_PRODLIST_IMG_VIEW_H_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_SHOW_1"]			= "S_MAIN_BEST_LIST4_SHOW_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_SHOW_2"]			= "S_MAIN_BEST_LIST4_SHOW_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_SHOW_3"]			= "S_MAIN_BEST_LIST4_SHOW_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_SHOW_4"]			= "S_MAIN_BEST_LIST4_SHOW_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_SHOW_5"]			= "S_MAIN_BEST_LIST4_SHOW_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_SHOW_6"]			= "S_MAIN_BEST_LIST4_SHOW_6";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_SHOW_7"]			= "S_MAIN_BEST_LIST4_SHOW_7";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_SHOW_8"]			= "S_MAIN_BEST_LIST4_SHOW_8";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_COLOR_1"]			= "S_MAIN_BEST_LIST4_COLOR_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_COLOR_2"]			= "S_MAIN_BEST_LIST4_COLOR_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_COLOR_3"]			= "S_MAIN_BEST_LIST4_COLOR_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_COLOR_4"]			= "S_MAIN_BEST_LIST4_COLOR_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_COLOR_5"]			= "S_MAIN_BEST_LIST4_COLOR_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_COLOR_6"]			= "S_MAIN_BEST_LIST4_COLOR_6";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_COLOR_7"]			= "S_MAIN_BEST_LIST4_COLOR_7";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_COLOR_8"]			= "S_MAIN_BEST_LIST4_COLOR_8";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_WORD_ALIGN"]		= "S_MAIN_BEST_LIST4_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_MONEY_TYPE"]		= "S_MAIN_BEST_LIST4_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_MONEY_ICON"]		= "S_MAIN_BEST_LIST4_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_TURN_USE"]			= "S_MAIN_BEST_LIST4_TURN_USE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_TITLE_SHOW_USE"]	= "S_MAIN_BEST_LIST4_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_TITLE_FILE_NAME"]	= "S_MAIN_BEST_LIST4_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST4_TITLE_MAXSIZE"]		= "S_MAIN_BEST_LIST4_TITLE_MAXSIZE";

// 사용자 정의 베스트 상품5
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_USE"]				= "S_ARY_MAIN_PRODLIST_USE[5]";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_NAME"]				= "S_MAIN_PRODLIST_TIT_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_DESIGN"]			= "S_MAIN_BEST_LIST5_DESIGN";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_SIZE_W"]			= "S_MAIN_PRODLIST_IMG_SIZE_W_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_SIZE_H"]			= "S_MAIN_PRODLIST_IMG_SIZE_H_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_VIEW_W"]			= "S_MAIN_PRODLIST_IMG_VIEW_W_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_VIEW_H"]			= "S_MAIN_PRODLIST_IMG_VIEW_H_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_SHOW_1"]			= "S_MAIN_BEST_LIST5_SHOW_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_SHOW_2"]			= "S_MAIN_BEST_LIST5_SHOW_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_SHOW_3"]			= "S_MAIN_BEST_LIST5_SHOW_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_SHOW_4"]			= "S_MAIN_BEST_LIST5_SHOW_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_SHOW_5"]			= "S_MAIN_BEST_LIST5_SHOW_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_SHOW_6"]			= "S_MAIN_BEST_LIST5_SHOW_6";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_SHOW_7"]			= "S_MAIN_BEST_LIST5_SHOW_7";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_SHOW_8"]			= "S_MAIN_BEST_LIST5_SHOW_8";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_COLOR_1"]			= "S_MAIN_BEST_LIST5_COLOR_1";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_COLOR_2"]			= "S_MAIN_BEST_LIST5_COLOR_2";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_COLOR_3"]			= "S_MAIN_BEST_LIST5_COLOR_3";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_COLOR_4"]			= "S_MAIN_BEST_LIST5_COLOR_4";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_COLOR_5"]			= "S_MAIN_BEST_LIST5_COLOR_5";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_COLOR_6"]			= "S_MAIN_BEST_LIST5_COLOR_6";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_COLOR_7"]			= "S_MAIN_BEST_LIST5_COLOR_7";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_COLOR_8"]			= "S_MAIN_BEST_LIST5_COLOR_8";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_WORD_ALIGN"]		= "S_MAIN_BEST_LIST5_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_MONEY_TYPE"]		= "S_MAIN_BEST_LIST5_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_MONEY_ICON"]		= "S_MAIN_BEST_LIST5_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_TURN_USE"]			= "S_MAIN_BEST_LIST5_TURN_USE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_TITLE_SHOW_USE"]	= "S_MAIN_BEST_LIST5_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_TITLE_FILE_NAME"]	= "S_MAIN_BEST_LIST5_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_ZL"]["ZL_BEST_LIST5_TITLE_MAXSIZE"]		= "S_MAIN_BEST_LIST5_TITLE_MAXSIZE";

// 상품리스트 - 상품리스트
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_DESIGN"]			= "S_PRODLIST_DESIGN";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_SIZE_W"]			= "S_PRODLIST_IMG_SIZE_W";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_SIZE_H"]			= "S_PRODLIST_IMG_SIZE_H";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_VIEW_W"]			= "S_PRODLIST_IMG_VIEW_W";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_VIEW_H"]			= "S_PRODLIST_IMG_VIEW_H";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_SHOW_1"]			= "S_PRODLIST_SHOW_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_SHOW_2"]			= "S_PRODLIST_SHOW_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_SHOW_3"]			= "S_PRODLIST_SHOW_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_SHOW_4"]			= "S_PRODLIST_SHOW_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_SHOW_5"]			= "S_PRODLIST_SHOW_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_SHOW_6"]			= "S_PRODLIST_SHOW_6";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_SHOW_7"]			= "S_PRODLIST_SHOW_7";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_SHOW_8"]			= "S_PRODLIST_SHOW_8";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_COLOR_1"]		= "S_PRODLIST_COLOR_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_COLOR_2"]		= "S_PRODLIST_COLOR_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_COLOR_3"]		= "S_PRODLIST_COLOR_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_COLOR_4"]		= "S_PRODLIST_COLOR_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_COLOR_5"]		= "S_PRODLIST_COLOR_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_COLOR_6"]		= "S_PRODLIST_COLOR_6";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_COLOR_7"]		= "S_PRODLIST_COLOR_7";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_COLOR_8"]		= "S_PRODLIST_COLOR_8";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_WORD_ALIGN"]		= "S_PRODLIST_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_MONEY_TYPE"]		= "S_PRODLIST_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_MONEY_ICON"]		= "S_PRODLIST_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_TURN_USE"]		= "S_PRODLIST_TURN_USE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_TITLE_SHOW_USE"]	= "S_PRODLIST_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_TITLE_FILE_NAME"]= "S_PRODLIST_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1000_TITLE_MAXSIZE"]	= "S_PRODLIST_TITLE_MAXSIZE";

// 사용자 정의 베스트 상품1(상품리스트)
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_USE"]				= "S_ARY_SUB_PRODLIST_USE[1]";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_NAME"]				= "S_SUB_PRODLIST_TIT_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_DESIGN"]			= "S_SUB_BEST_LIST1_DESIGN";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_SIZE_W"]			= "S_SUB_PRODLIST_IMG_SIZE_W_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_SIZE_H"]			= "S_SUB_PRODLIST_IMG_SIZE_H_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_VIEW_W"]			= "S_SUB_PRODLIST_IMG_VIEW_W_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_VIEW_H"]			= "S_SUB_PRODLIST_IMG_VIEW_H_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_SHOW_1"]			= "S_SUB_BEST_LIST1_SHOW_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_SHOW_2"]			= "S_SUB_BEST_LIST1_SHOW_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_SHOW_3"]			= "S_SUB_BEST_LIST1_SHOW_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_SHOW_4"]			= "S_SUB_BEST_LIST1_SHOW_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_SHOW_5"]			= "S_SUB_BEST_LIST1_SHOW_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_SHOW_6"]			= "S_SUB_BEST_LIST1_SHOW_6";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_SHOW_7"]			= "S_SUB_BEST_LIST1_SHOW_7";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_SHOW_8"]			= "S_SUB_BEST_LIST1_SHOW_8";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_COLOR_1"]			= "S_SUB_BEST_LIST1_COLOR_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_COLOR_2"]			= "S_SUB_BEST_LIST1_COLOR_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_COLOR_3"]			= "S_SUB_BEST_LIST1_COLOR_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_COLOR_4"]			= "S_SUB_BEST_LIST1_COLOR_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_COLOR_5"]			= "S_SUB_BEST_LIST1_COLOR_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_COLOR_6"]			= "S_SUB_BEST_LIST1_COLOR_6";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_COLOR_7"]			= "S_SUB_BEST_LIST1_COLOR_7";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_COLOR_8"]			= "S_SUB_BEST_LIST1_COLOR_8";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_WORD_ALIGN"]		= "S_SUB_BEST_LIST1_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_MONEY_TYPE"]		= "S_SUB_BEST_LIST1_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_MONEY_ICON"]		= "S_SUB_BEST_LIST1_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_TURN_USE"]			= "S_SUB_BEST_LIST1_TURN_USE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_TITLE_SHOW_USE"]	= "S_SUB_BEST_LIST1_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_TITLE_FILE_NAME"]	= "S_SUB_BEST_LIST1_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST1_TITLE_MAXSIZE"]		= "S_SUB_BEST_LIST1_TITLE_MAXSIZE";

//$_CONF_FIELD_NAME["SKIN_PL"]["PL_TOP_MENU"]					= "S_SUB_TOP_MENU";

// 사용자 정의 베스트 상품2
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_USE"]				= "S_ARY_SUB_PRODLIST_USE[2]";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_NAME"]				= "S_SUB_PRODLIST_TIT_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_DESIGN"]			= "S_SUB_BEST_LIST2_DESIGN";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_SIZE_W"]			= "S_SUB_PRODLIST_IMG_SIZE_W_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_SIZE_H"]			= "S_SUB_PRODLIST_IMG_SIZE_H_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_VIEW_W"]			= "S_SUB_PRODLIST_IMG_VIEW_W_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_VIEW_H"]			= "S_SUB_PRODLIST_IMG_VIEW_H_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_SHOW_1"]			= "S_SUB_BEST_LIST2_SHOW_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_SHOW_2"]			= "S_SUB_BEST_LIST2_SHOW_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_SHOW_3"]			= "S_SUB_BEST_LIST2_SHOW_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_SHOW_4"]			= "S_SUB_BEST_LIST2_SHOW_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_SHOW_5"]			= "S_SUB_BEST_LIST2_SHOW_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_SHOW_6"]			= "S_SUB_BEST_LIST2_SHOW_6";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_SHOW_7"]			= "S_SUB_BEST_LIST2_SHOW_7";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_SHOW_8"]			= "S_SUB_BEST_LIST2_SHOW_8";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_COLOR_1"]			= "S_SUB_BEST_LIST2_COLOR_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_COLOR_2"]			= "S_SUB_BEST_LIST2_COLOR_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_COLOR_3"]			= "S_SUB_BEST_LIST2_COLOR_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_COLOR_4"]			= "S_SUB_BEST_LIST2_COLOR_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_COLOR_5"]			= "S_SUB_BEST_LIST2_COLOR_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_COLOR_6"]			= "S_SUB_BEST_LIST2_COLOR_6";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_COLOR_7"]			= "S_SUB_BEST_LIST2_COLOR_7";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_COLOR_8"]			= "S_SUB_BEST_LIST2_COLOR_8";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_WORD_ALIGN"]		= "S_SUB_BEST_LIST2_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_MONEY_TYPE"]		= "S_SUB_BEST_LIST2_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_MONEY_ICON"]		= "S_SUB_BEST_LIST2_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_TURN_USE"]			= "S_SUB_BEST_LIST2_TURN_USE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_TITLE_SHOW_USE"]	= "S_SUB_BEST_LIST2_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_TITLE_FILE_NAME"]	= "S_SUB_BEST_LIST2_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST2_TITLE_MAXSIZE"]		= "S_SUB_BEST_LIST2_TITLE_MAXSIZE";

// 사용자 정의 베스트 상품3
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_USE"]				= "S_ARY_SUB_PRODLIST_USE[3]";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_NAME"]				= "S_SUB_PRODLIST_TIT_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_DESIGN"]			= "S_SUB_BEST_LIST3_DESIGN";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_SIZE_W"]			= "S_SUB_PRODLIST_IMG_SIZE_W_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_SIZE_H"]			= "S_SUB_PRODLIST_IMG_SIZE_H_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_VIEW_W"]			= "S_SUB_PRODLIST_IMG_VIEW_W_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_VIEW_H"]			= "S_SUB_PRODLIST_IMG_VIEW_H_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_SHOW_1"]			= "S_SUB_BEST_LIST3_SHOW_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_SHOW_2"]			= "S_SUB_BEST_LIST3_SHOW_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_SHOW_3"]			= "S_SUB_BEST_LIST3_SHOW_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_SHOW_4"]			= "S_SUB_BEST_LIST3_SHOW_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_SHOW_5"]			= "S_SUB_BEST_LIST3_SHOW_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_SHOW_6"]			= "S_SUB_BEST_LIST3_SHOW_6";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_SHOW_7"]			= "S_SUB_BEST_LIST3_SHOW_7";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_SHOW_8"]			= "S_SUB_BEST_LIST3_SHOW_8";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_COLOR_1"]			= "S_SUB_BEST_LIST3_COLOR_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_COLOR_2"]			= "S_SUB_BEST_LIST3_COLOR_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_COLOR_3"]			= "S_SUB_BEST_LIST3_COLOR_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_COLOR_4"]			= "S_SUB_BEST_LIST3_COLOR_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_COLOR_5"]			= "S_SUB_BEST_LIST3_COLOR_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_COLOR_6"]			= "S_SUB_BEST_LIST3_COLOR_6";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_COLOR_7"]			= "S_SUB_BEST_LIST3_COLOR_7";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_COLOR_8"]			= "S_SUB_BEST_LIST3_COLOR_8";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_WORD_ALIGN"]		= "S_SUB_BEST_LIST3_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_MONEY_TYPE"]		= "S_SUB_BEST_LIST3_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_MONEY_ICON"]		= "S_SUB_BEST_LIST3_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_TURN_USE"]			= "S_SUB_BEST_LIST3_TURN_USE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_TITLE_SHOW_USE"]	= "S_SUB_BEST_LIST3_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_TITLE_FILE_NAME"]	= "S_SUB_BEST_LIST3_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST3_TITLE_MAXSIZE"]		= "S_SUB_BEST_LIST3_TITLE_MAXSIZE";

// 사용자 정의 베스트 상품4
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_USE"]				= "S_ARY_SUB_PRODLIST_USE[4]";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_NAME"]				= "S_SUB_PRODLIST_TIT_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_DESIGN"]			= "S_SUB_BEST_LIST4_DESIGN";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SIZE_W"]			= "S_SUB_PRODLIST_IMG_SIZE_W_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SIZE_H"]			= "S_SUB_PRODLIST_IMG_SIZE_H_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_VIEW_W"]			= "S_SUB_PRODLIST_IMG_VIEW_W_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_VIEW_H"]			= "S_SUB_PRODLIST_IMG_VIEW_H_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_1"]			= "S_SUB_BEST_LIST5_SHOW_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_2"]			= "S_SUB_BEST_LIST5_SHOW_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_3"]			= "S_SUB_BEST_LIST5_SHOW_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_4"]			= "S_SUB_BEST_LIST5_SHOW_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_5"]			= "S_SUB_BEST_LIST5_SHOW_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_6"]			= "S_SUB_BEST_LIST5_SHOW_6";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_7"]			= "S_SUB_BEST_LIST5_SHOW_7";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_8"]			= "S_SUB_BEST_LIST5_SHOW_8";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_1"]			= "S_SUB_BEST_LIST5_COLOR_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_2"]			= "S_SUB_BEST_LIST5_COLOR_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_3"]			= "S_SUB_BEST_LIST5_COLOR_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_4"]			= "S_SUB_BEST_LIST5_COLOR_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_5"]			= "S_SUB_BEST_LIST5_COLOR_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_6"]			= "S_SUB_BEST_LIST5_COLOR_6";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_7"]			= "S_SUB_BEST_LIST5_COLOR_7";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_8"]			= "S_SUB_BEST_LIST5_COLOR_8";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_WORD_ALIGN"]		= "S_SUB_BEST_LIST5_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_MONEY_TYPE"]		= "S_SUB_BEST_LIST5_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_MONEY_ICON"]		= "S_SUB_BEST_LIST5_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_TURN_USE"]			= "S_SUB_BEST_LIST5_TURN_USE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST4_TITLE_SHOW_USE"]	= "S_SUB_BEST_LIST4_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST4_TITLE_FILE_NAME"]	= "S_SUB_BEST_LIST4_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST4_TITLE_MAXSIZE"]		= "S_SUB_BEST_LIST4_TITLE_MAXSIZE";

// 사용자 정의 베스트 상품5
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_USE"]				= "S_ARY_SUB_PRODLIST_USE[5]";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_NAME"]				= "S_SUB_PRODLIST_TIT_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_DESIGN"]			= "S_SUB_BEST_LIST5_DESIGN";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SIZE_W"]			= "S_SUB_PRODLIST_IMG_SIZE_W_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SIZE_H"]			= "S_SUB_PRODLIST_IMG_SIZE_H_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_VIEW_W"]			= "S_SUB_PRODLIST_IMG_VIEW_W_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_VIEW_H"]			= "S_SUB_PRODLIST_IMG_VIEW_H_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_1"]			= "S_SUB_BEST_LIST5_SHOW_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_2"]			= "S_SUB_BEST_LIST5_SHOW_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_3"]			= "S_SUB_BEST_LIST5_SHOW_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_4"]			= "S_SUB_BEST_LIST5_SHOW_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_5"]			= "S_SUB_BEST_LIST5_SHOW_5";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_6"]			= "S_SUB_BEST_LIST5_SHOW_6";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_7"]			= "S_SUB_BEST_LIST5_SHOW_7";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_SHOW_8"]			= "S_SUB_BEST_LIST5_SHOW_8";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_1"]			= "S_SUB_BEST_LIST5_COLOR_1";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_2"]			= "S_SUB_BEST_LIST5_COLOR_2";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_3"]			= "S_SUB_BEST_LIST5_COLOR_3";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_4"]			= "S_SUB_BEST_LIST5_COLOR_4";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_6"]			= "S_SUB_BEST_LIST5_COLOR_6";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_7"]			= "S_SUB_BEST_LIST5_COLOR_7";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_COLOR_8"]			= "S_SUB_BEST_LIST5_COLOR_8";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_WORD_ALIGN"]		= "S_SUB_BEST_LIST5_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_MONEY_TYPE"]		= "S_SUB_BEST_LIST5_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_MONEY_ICON"]		= "S_SUB_BEST_LIST5_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_TURN_USE"]			= "S_SUB_BEST_LIST5_TURN_USE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_TITLE_SHOW_USE"]	= "S_SUB_BEST_LIST5_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_TITLE_FILE_NAME"]	= "S_SUB_BEST_LIST5_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_BEST_LIST5_TITLE_MAXSIZE"]		= "S_SUB_BEST_LIST5_TITLE_MAXSIZE";

/* 상품리스트 이미지 설정 */
$_CONF_FIELD_NAME["SKIN_PL"]["PL_IMG_SIZE_W"]		= "S_PRODUCT_LIST_ISW";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_IMG_SIZE_H"]		= "S_PRODUCT_LIST_ISH";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_IMG_VIEW_W"]		= "S_PRODUCT_LIST_IVW";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_IMG_VIEW_H"]		= "S_PRODUCT_LIST_IVH";

/* 상품 TOP 버튼 설정 */
$_CONF_FIELD_NAME["SKIN_PL"]["PL_TOP_USE_CATE_IMG"]		= "S_PRODUCT_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_PL"]["PL_NAVI_USE_OP"]			= "S_PRODUCT_NAVI_USE_OP";	//네비게이션 사용유무
$_CONF_FIELD_NAME["SKIN_PL"]["PL_TOP_USE_OP"]			= "S_PRODUCT_TOP_USE_OP";	//사용유무
$_CONF_FIELD_NAME["SKIN_PL"]["PL_TOP_CAT_OP"]			= "S_PRODUCT_TOP_CAT_OP";	//카테고리몇차까지 사용


/* 상품검색 */
$_CONF_FIELD_NAME["SKIN_PS"]["PS_TOP_USE_CATE_IMG"]	= "S_PRODSEA_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_PS"]["PS_TOP_USE_OP"]		= "S_PRODSEA_TOP_USE_OP"; //사용유무
$_CONF_FIELD_NAME["SKIN_PS"]["PS_TOP_CAT_OP"]		= "S_PRODSEA_TOP_CAT_OP"; //카테고리몇차까지 사용

/* 브랜드 메인화면 TOP IMAGE 설정 */
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_TOP_USE_CATE_IMG"]		= "S_BRAND_MAIN_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_TOP_USE_OP"]			= "S_BRAND_MAIN_TOP_USE_OP";	//사용유무
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_TOP_CAT_OP"]			= "S_BRAND_MAIN_TOP_CAT_OP";	//카테고리몇차까지 사용
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_TOP_USE_CATE_HTML"]	= "S_BRAND_MAIN_TOP_HTML";		//HTML 파일 경로


/* 브랜드 세부화면 TOP IMAGE 설정 */
$_CONF_FIELD_NAME["SKIN_PH"]["PH_TOP_USE_CATE_IMG"]		= "S_BRAND_LIST_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_TOP_USE_OP"]			= "S_BRAND_LIST_TOP_USE_OP";	//사용유무
$_CONF_FIELD_NAME["SKIN_PH"]["PH_TOP_CAT_OP"]			= "S_BRAND_LIST_TOP_CAT_OP";	//카테고리몇차까지 사용
$_CONF_FIELD_NAME["SKIN_PH"]["PH_TOP_USE_CATE_HTML"]	= "S_BRAND_LIST_TOP_HTML";		//HTML 파일 경로

/* 상품 카테고리별 이미지 생성
$_CONF_FIELD_NAME["SKIN_PL"]["PL_TOP_USE_CATE_상품코드_IMG"]	= "S_PRODUCT_TOP_카테고리코드_IMG";
*/

/* 상품 서브카테고리 사용여부 설정*/
$_CONF_FIELD_NAME["SKIN_PL"]["PL_SUB_CATE_USE"]		= "S_PRODUCT_SUB_CATE_USE";		// 사용 여부
$_CONF_FIELD_NAME["SKIN_PL"]["PL_SUB_CATE_VIEW"]	= "S_PRODUCT_SUB_CATE_VIEW";	//몇차까지 보일껀지
$_CONF_FIELD_NAME["SKIN_PL"]["PL_SUB_CATE_DESIGN"]	= "S_PRODUCT_SUB_CATE_DESIGN";	//디자인번호
$_CONF_FIELD_NAME["SKIN_PL"]["PL_SUB_CATE_L1_MODE"]	= "S_PRODUCT_CATE_L1_MODE"; //카테고리1 모드(숨김=N,텍스트=T,이미지=I))
$_CONF_FIELD_NAME["SKIN_PL"]["PL_SUB_CATE_L2_MODE"]	= "S_PRODUCT_CATE_L2_MODE"; //카테고리2 모드(숨김=N,텍스트=T,이미지=I))
$_CONF_FIELD_NAME["SKIN_PL"]["PL_SUB_CATE_L3_MODE"]	= "S_PRODUCT_CATE_L3_MODE"; //카테고리3 모드(숨김=N,텍스트=T,이미지=I))
$_CONF_FIELD_NAME["SKIN_PL"]["PL_SUB_CATE_L4_MODE"]	= "S_PRODUCT_CATE_L4_MODE"; //카테고리4 모드(숨김=N,텍스트=T,이미지=I))

/* 브랜드 세부화면 서브카테고리 사용여부 설정*/
$_CONF_FIELD_NAME["SKIN_PH"]["PH_SUB_CATE_USE"]		= "S_BRAND_LIST_SUB_CATE_USE";		// 사용 여부
$_CONF_FIELD_NAME["SKIN_PH"]["PH_SUB_CATE_VIEW"]	= "S_BRAND_LIST_SUB_CATE_VIEW";	//몇차까지 보일껀지
$_CONF_FIELD_NAME["SKIN_PH"]["PH_SUB_CATE_DESIGN"]	= "S_BRAND_LIST_SUB_CATE_DESIGN";	//디자인번호
$_CONF_FIELD_NAME["SKIN_PH"]["PH_SUB_CATE_L1_MODE"]	= "S_BRAND_LIST_CATE_L1_MODE"; //카테고리1 모드(숨김=N,텍스트=T,이미지=I))
$_CONF_FIELD_NAME["SKIN_PH"]["PH_SUB_CATE_L2_MODE"]	= "S_BRAND_LIST_CATE_L2_MODE"; //카테고리2 모드(숨김=N,텍스트=T,이미지=I))
$_CONF_FIELD_NAME["SKIN_PH"]["PH_SUB_CATE_L3_MODE"]	= "S_BRAND_LIST_CATE_L3_MODE"; //카테고리3 모드(숨김=N,텍스트=T,이미지=I))
$_CONF_FIELD_NAME["SKIN_PH"]["PH_SUB_CATE_L4_MODE"]	= "S_BRAND_LIST_CATE_L4_MODE"; //카테고리4 모드(숨김=N,텍스트=T,이미지=I))

/* 상품뷰(ProdView) SNS 설정 */
$_CONF_FIELD_NAME["SKIN_PV"]["PV_SNS_USE"]			= "S_PRODUCT_VIEW_SNS_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_SNS_FACEBOOK"]		= "S_PRODUCT_VIEW_SNS_FACEBOOK";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_SNS_TWITTER"]		= "S_PRODUCT_VIEW_SNS_TWITTER";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_SNS_M2DAY"]		= "S_PRODUCT_VIEW_SNS_M2DAY";

/* 상품뷰(ProdView) 이미지 설정 */
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMAGE_DESIGN"]		= "S_PRODUCT_VIEW_IMAGE_DESIGN";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMAGE_SHOW_TYPE"]	= "S_PRODUCT_VIEW_IMAGE_SHOW_TYPE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMAGE_ZOOM_USE"]	= "S_PRODUCT_VIEW_IZOOM_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_VIEW_W"]		= "S_PRODUCT_VIEW_IMG_VIEW_W";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_VIEW_H"]		= "S_PRODUCT_VIEW_IMG_VIEW_H";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BBS_REVIEW_USE"]	= "S_PRODUCT_VIEW_BBS_REVIEW_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BBS_QNA_USE"]		= "S_PRODUCT_VIEW_BBS_QNA_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_SIZE_W"]		= "S_PRODUCT_VIEW_ISW";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_SIZE_H"]		= "S_PRODUCT_VIEW_ISH";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_POP_IMG_SIZE_W"]	= "S_PRODUCT_VIEW_PISW";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_POP_IMG_SIZE_H"]	= "S_PRODUCT_VIEW_PISH";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_AFTER_YN"]			= "S_PRODUCT_VIEW_AFTER_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_QNA_YN"]			= "S_PRODUCT_VIEW_QNA_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_RELATED_YN"]		= "S_PRODUCT_VIEW_RELATED_USE";

$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_MULTY_SIZE_W"]		= "S_PRODUCT_IMG_MULTY_SIZE_W";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_MULTY_SIZE_H"]		= "S_PRODUCT_IMG_MULTY_SIZE_H";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_MULTY_VIEW_W"]		= "S_PRODUCT_IMG_MULTY_VIEW_W";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_MULTY_VIEW_H"]		= "S_PRODUCT_IMG_MULTY_VIEW_H";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_MULTY_CHANGE"]		= "S_PRODUCT_IMG_MULTY_CHANGE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_ZOOM_SIZE_W"]		= "S_PRODUCT_IMG_ZOOM_SIZE_W";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_ZOOM_SIZE_H"]		= "S_PRODUCT_IMG_ZOOM_SIZE_H";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_ZOOM_VIEW_W"]		= "S_PRODUCT_IMG_ZOOM_VIEW_W";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_ZOOM_VIEW_H"]		= "S_PRODUCT_IMG_ZOOM_VIEW_H";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_IMG_ZOOM_POSITION"]	= "S_PRODUCT_IMG_ZOOM_POSITION";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BBS_REVIEW_USE"]		= "S_PRODUCT_BBS_REVIEW_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BBS_QNA_USE"]			= "S_PRODUCT_BBS_QNA_USE";

// 상품리스트 - 상품리스트1
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_USE"]				= "S_PRODUCT_VIEW_BEST_LIST1_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_NAME"]				= "S_PRODUCT_VIEW_BEST_LIST1_NAME";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_DESIGN"]			= "S_PRODUCT_VIEW_BEST_LIST1_DESIGN";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_SIZE_W"]			= "S_PRODUCT_VIEW_BEST_LIST1_SIZE_W";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_SIZE_H"]			= "S_PRODUCT_VIEW_BEST_LIST1_SIZE_H";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_VIEW_W"]			= "S_PRODUCT_VIEW_BEST_LIST1_VIEW_W";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_VIEW_H"]			= "S_PRODUCT_VIEW_BEST_LIST1_VIEW_H";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_SHOW_1"]			= "S_PRODUCT_VIEW_BEST_LIST1_SHOW_1";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_SHOW_2"]			= "S_PRODUCT_VIEW_BEST_LIST1_SHOW_2";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_SHOW_3"]			= "S_PRODUCT_VIEW_BEST_LIST1_SHOW_3";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_SHOW_4"]			= "S_PRODUCT_VIEW_BEST_LIST1_SHOW_4";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_SHOW_5"]			= "S_PRODUCT_VIEW_BEST_LIST1_SHOW_5";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_SHOW_6"]			= "S_PRODUCT_VIEW_BEST_LIST1_SHOW_6";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_SHOW_7"]			= "S_PRODUCT_VIEW_BEST_LIST1_SHOW_7";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_SHOW_8"]			= "S_PRODUCT_VIEW_BEST_LIST1_SHOW_8";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_COLOR_1"]			= "S_PRODUCT_VIEW_BEST_LIST1_COLOR_1";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_COLOR_2"]			= "S_PRODUCT_VIEW_BEST_LIST1_COLOR_2";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_COLOR_3"]			= "S_PRODUCT_VIEW_BEST_LIST1_COLOR_3";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_COLOR_4"]			= "S_PRODUCT_VIEW_BEST_LIST1_COLOR_4";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_COLOR_6"]			= "S_PRODUCT_VIEW_BEST_LIST1_COLOR_6";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_COLOR_7"]			= "S_PRODUCT_VIEW_BEST_LIST1_COLOR_7";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_COLOR_8"]			= "S_PRODUCT_VIEW_BEST_LIST1_COLOR_8";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_WORD_ALIGN"]		= "S_PRODUCT_VIEW_BEST_LIST1_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_MONEY_TYPE"]		= "S_PRODUCT_VIEW_BEST_LIST1_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_MONEY_ICON"]		= "S_PRODUCT_VIEW_BEST_LIST1_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_TURN_USE"]			= "S_PRODUCT_VIEW_BEST_LIST1_TURN_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_TITLE_SHOW_USE"]	= "S_PRODUCT_VIEW_BEST_LIST1_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_TITLE_FILE_NAME"]	= "S_PRODUCT_VIEW_BEST_LIST1_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST1_TITLE_MAXSIZE"]		= "S_PRODUCT_VIEW_BEST_LIST1_TITLE_MAXSIZE";

// 상품리스트 - 상품리스트2
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_USE"]				= "S_PRODUCT_VIEW_BEST_LIST2_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_NAME"]				= "S_PRODUCT_VIEW_BEST_LIST2_NAME";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_DESIGN"]			= "S_PRODUCT_VIEW_BEST_LIST2_DESIGN";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_SIZE_W"]			= "S_PRODUCT_VIEW_BEST_LIST2_SIZE_W";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_SIZE_H"]			= "S_PRODUCT_VIEW_BEST_LIST2_SIZE_H";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_VIEW_W"]			= "S_PRODUCT_VIEW_BEST_LIST2_VIEW_W";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_VIEW_H"]			= "S_PRODUCT_VIEW_BEST_LIST2_VIEW_H";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_SHOW_1"]			= "S_PRODUCT_VIEW_BEST_LIST2_SHOW_1";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_SHOW_2"]			= "S_PRODUCT_VIEW_BEST_LIST2_SHOW_2";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_SHOW_3"]			= "S_PRODUCT_VIEW_BEST_LIST2_SHOW_3";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_SHOW_4"]			= "S_PRODUCT_VIEW_BEST_LIST2_SHOW_4";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_SHOW_5"]			= "S_PRODUCT_VIEW_BEST_LIST2_SHOW_5";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_SHOW_6"]			= "S_PRODUCT_VIEW_BEST_LIST2_SHOW_6";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_SHOW_7"]			= "S_PRODUCT_VIEW_BEST_LIST2_SHOW_7";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_SHOW_8"]			= "S_PRODUCT_VIEW_BEST_LIST2_SHOW_8";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_COLOR_1"]			= "S_PRODUCT_VIEW_BEST_LIST2_COLOR_1";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_COLOR_2"]			= "S_PRODUCT_VIEW_BEST_LIST2_COLOR_2";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_COLOR_3"]			= "S_PRODUCT_VIEW_BEST_LIST2_COLOR_3";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_COLOR_4"]			= "S_PRODUCT_VIEW_BEST_LIST2_COLOR_4";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_COLOR_5"]			= "S_PRODUCT_VIEW_BEST_LIST2_COLOR_5";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_COLOR_6"]			= "S_PRODUCT_VIEW_BEST_LIST2_COLOR_6";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_COLOR_7"]			= "S_PRODUCT_VIEW_BEST_LIST2_COLOR_7";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_COLOR_8"]			= "S_PRODUCT_VIEW_BEST_LIST2_COLOR_8";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_WORD_ALIGN"]		= "S_PRODUCT_VIEW_BEST_LIST2_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_MONEY_TYPE"]		= "S_PRODUCT_VIEW_BEST_LIST2_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_MONEY_ICON"]		= "S_PRODUCT_VIEW_BEST_LIST2_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_TURN_USE"]			= "S_PRODUCT_VIEW_BEST_LIST2_TURN_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_TITLE_SHOW_USE"]	= "S_PRODUCT_VIEW_BEST_LIST2_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_TITLE_FILE_NAME"]	= "S_PRODUCT_VIEW_BEST_LIST2_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST2_TITLE_MAXSIZE"]		= "S_PRODUCT_VIEW_BEST_LIST2_TITLE_MAXSIZE";

// 상품리스트 - 상품리스트3
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_USE"]				= "S_PRODUCT_VIEW_BEST_LIST3_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_NAME"]				= "S_PRODUCT_VIEW_BEST_LIST3_NAME";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_DESIGN"]			= "S_PRODUCT_VIEW_BEST_LIST3_DESIGN";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_SIZE_W"]			= "S_PRODUCT_VIEW_BEST_LIST3_SIZE_W";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_SIZE_H"]			= "S_PRODUCT_VIEW_BEST_LIST3_SIZE_H";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_VIEW_W"]			= "S_PRODUCT_VIEW_BEST_LIST3_VIEW_W";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_VIEW_H"]			= "S_PRODUCT_VIEW_BEST_LIST3_VIEW_H";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_SHOW_1"]			= "S_PRODUCT_VIEW_BEST_LIST3_SHOW_1";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_SHOW_2"]			= "S_PRODUCT_VIEW_BEST_LIST3_SHOW_2";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_SHOW_3"]			= "S_PRODUCT_VIEW_BEST_LIST3_SHOW_3";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_SHOW_4"]			= "S_PRODUCT_VIEW_BEST_LIST3_SHOW_4";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_SHOW_5"]			= "S_PRODUCT_VIEW_BEST_LIST3_SHOW_5";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_SHOW_6"]			= "S_PRODUCT_VIEW_BEST_LIST3_SHOW_6";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_SHOW_7"]			= "S_PRODUCT_VIEW_BEST_LIST3_SHOW_7";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_SHOW_8"]			= "S_PRODUCT_VIEW_BEST_LIST3_SHOW_8";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_COLOR_1"]			= "S_PRODUCT_VIEW_BEST_LIST3_COLOR_1";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_COLOR_2"]			= "S_PRODUCT_VIEW_BEST_LIST3_COLOR_2";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_COLOR_3"]			= "S_PRODUCT_VIEW_BEST_LIST3_COLOR_3";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_COLOR_4"]			= "S_PRODUCT_VIEW_BEST_LIST3_COLOR_4";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_COLOR_5"]			= "S_PRODUCT_VIEW_BEST_LIST3_COLOR_5";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_COLOR_6"]			= "S_PRODUCT_VIEW_BEST_LIST3_COLOR_6";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_COLOR_7"]			= "S_PRODUCT_VIEW_BEST_LIST3_COLOR_7";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_COLOR_8"]			= "S_PRODUCT_VIEW_BEST_LIST3_COLOR_8";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_WORD_ALIGN"]		= "S_PRODUCT_VIEW_BEST_LIST3_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_MONEY_TYPE"]		= "S_PRODUCT_VIEW_BEST_LIST3_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_MONEY_ICON"]		= "S_PRODUCT_VIEW_BEST_LIST3_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_TURN_USE"]			= "S_PRODUCT_VIEW_BEST_LIST3_TURN_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_TITLE_SHOW_USE"]	= "S_PRODUCT_VIEW_BEST_LIST3_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_TITLE_FILE_NAME"]	= "S_PRODUCT_VIEW_BEST_LIST3_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_PV"]["PV_BEST_LIST3_TITLE_MAXSIZE"]		= "S_PRODUCT_VIEW_BEST_LIST3_TITLE_MAXSIZE";

// 상품 - 브랜드 메인화면
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_USE"]				= "S_PRODUCT_BRAND_MAIN1_USE";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_NAME"]				= "S_PRODUCT_BRAND_MAIN1_NAME";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_DESIGN"]			= "S_PRODUCT_BRAND_MAIN1_DESIGN";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_SIZE_W"]			= "S_PRODUCT_BRAND_MAIN1_IMG_SIZE_W";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_SIZE_H"]			= "S_PRODUCT_BRAND_MAIN1_IMG_SIZE_H";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_VIEW_W"]			= "S_PRODUCT_BRAND_MAIN1_IMG_VIEW_W";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_VIEW_H"]			= "S_PRODUCT_BRAND_MAIN1_IMG_VIEW_H";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_SHOW_1"]			= "S_PRODUCT_BRAND_MAIN1_SHOW_1";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_SHOW_2"]			= "S_PRODUCT_BRAND_MAIN1_SHOW_2";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_SHOW_3"]			= "S_PRODUCT_BRAND_MAIN1_SHOW_3";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_SHOW_4"]			= "S_PRODUCT_BRAND_MAIN1_SHOW_4";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_SHOW_5"]			= "S_PRODUCT_BRAND_MAIN1_SHOW_5";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_SHOW_6"]			= "S_PRODUCT_BRAND_MAIN1_SHOW_6";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_SHOW_7"]			= "S_PRODUCT_BRAND_MAIN1_SHOW_7";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_SHOW_8"]			= "S_PRODUCT_BRAND_MAIN1_SHOW_8";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_COLOR_1"]			= "S_PRODUCT_BRAND_MAIN1_COLOR_1";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_COLOR_2"]			= "S_PRODUCT_BRAND_MAIN1_COLOR_2";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_COLOR_3"]			= "S_PRODUCT_BRAND_MAIN1_COLOR_3";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_COLOR_4"]			= "S_PRODUCT_BRAND_MAIN1_COLOR_4";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_COLOR_5"]			= "S_PRODUCT_BRAND_MAIN1_COLOR_5";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_COLOR_6"]			= "S_PRODUCT_BRAND_MAIN1_COLOR_6";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_COLOR_7"]			= "S_PRODUCT_BRAND_MAIN1_COLOR_7";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_COLOR_8"]			= "S_PRODUCT_BRAND_MAIN1_COLOR_8";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_WORD_ALIGN"]		= "S_PRODUCT_BRAND_MAIN1_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_MONEY_TYPE"]		= "S_PRODUCT_BRAND_MAIN1_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_MONEY_ICON"]		= "S_PRODUCT_BRAND_MAIN1_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_TURN_USE"]			= "S_PRODUCT_BRAND_MAIN1_TURN_USE";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_TITLE_SHOW_USE"]	= "S_PRODUCT_BRAND_MAIN1_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_TITLE_FILE_NAME"]	= "S_PRODUCT_BRAND_MAIN1_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_PJ"]["PJ_BEST_LIST1_TITLE_MAXSIZE"]		= "S_PRODUCT_BRAND_MAIN1_TITLE_MAXSIZE";
// 브랜드 상품리스트 화면
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_USE"]			= "S_PRODUCT_BRAND_LIST1_USE";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_NAME"]			= "S_PRODUCT_BRAND_LIST1_NAME";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_DESIGN"]			= "S_PRODUCT_BRAND_LIST1_DESIGN";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_SIZE_W"]			= "S_PRODUCT_BRAND_LIST1_IMG_SIZE_W";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_SIZE_H"]			= "S_PRODUCT_BRAND_LIST1_IMG_SIZE_H";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_VIEW_W"]			= "S_PRODUCT_BRAND_LIST1_IMG_VIEW_W";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_VIEW_H"]			= "S_PRODUCT_BRAND_LIST1_IMG_VIEW_H";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_SHOW_1"]			= "S_PRODUCT_BRAND_LIST1_SHOW_1";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_SHOW_2"]			= "S_PRODUCT_BRAND_LIST1_SHOW_2";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_SHOW_3"]			= "S_PRODUCT_BRAND_LIST1_SHOW_3";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_SHOW_4"]			= "S_PRODUCT_BRAND_LIST1_SHOW_4";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_SHOW_5"]			= "S_PRODUCT_BRAND_LIST1_SHOW_5";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_SHOW_6"]			= "S_PRODUCT_BRAND_LIST1_SHOW_6";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_SHOW_7"]			= "S_PRODUCT_BRAND_LIST1_SHOW_7";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_SHOW_8"]			= "S_PRODUCT_BRAND_LIST1_SHOW_8";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_COLOR_1"]		= "S_PRODUCT_BRAND_LIST1_COLOR_1";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_COLOR_2"]		= "S_PRODUCT_BRAND_LIST1_COLOR_2";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_COLOR_3"]		= "S_PRODUCT_BRAND_LIST1_COLOR_3";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_COLOR_4"]		= "S_PRODUCT_BRAND_LIST1_COLOR_4";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_COLOR_5"]		= "S_PRODUCT_BRAND_LIST1_COLOR_5";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_COLOR_6"]		= "S_PRODUCT_BRAND_LIST1_COLOR_6";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_COLOR_7"]		= "S_PRODUCT_BRAND_LIST1_COLOR_7";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_COLOR_8"]		= "S_PRODUCT_BRAND_LIST1_COLOR_8";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_WORD_ALIGN"]		= "S_PRODUCT_BRAND_LIST1_WORD_ALIGN";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_MONEY_TYPE"]		= "S_PRODUCT_BRAND_LIST1_MONEY_TYPE";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_MONEY_ICON"]		= "S_PRODUCT_BRAND_LIST1_MONEY_ICON";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_TURN_USE"]		= "S_PRODUCT_BRAND_LIST1_TURN_USE";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_TITLE_SHOW_USE"]	= "S_PRODUCT_BRAND_LIST1_TITLE_SHOW_USE";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_TITLE_FILE_NAME"]= "S_PRODUCT_BRAND_LIST1_TITLE_FILE_NAME";
$_CONF_FIELD_NAME["SKIN_PH"]["PH_BEST_LIST1000_TITLE_MAXSIZE"]	= "S_PRODUCT_BRAND_LIST1_TITLE_MAXSIZE";

/* 상품관련 버튼 설정 */
$_CONF_FIELD_NAME["SKIN"]["P_BTN"]					= "S_PRODUCT_BTN_PATH";


/** MEMBER 관련 **/

/* TOP 통합 관리 옵션 설정*/
$_CONF_FIELD_NAME["SKIN_M"]["M_TOP_USE_OP"]			= "S_MEMBER_TOP_USE_OP";	// A -> 공통, C -> 각 페이지, N -> 사용 안함
$_CONF_FIELD_NAME["SKIN_M"]["M_TOP_IMG"]			= "S_MEMBER_TOP_IMG";		// 공통 이미지

/* 회원로그인 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_ML"]["ML_TOP_IMG"]			= "S_MEMBER_LOGIN_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_ML"]["ML_TOP_HTML"]			= "S_MEMBER_LOGIN_TOP_HTML";
$_CONF_FIELD_NAME["SKIN_ML"]["ML_IMAGE_DESIGN"]		= "S_MEMBER_LOGIN_IMAGE_DESIGN";

/* 회원가입약관 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_MT"]["MT_TOP_IMG"]			= "S_MEMBER_JOIN1_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_MT"]["MT_TOP_HTML"]			= "S_MEMBER_JOIN1_TOP_HTML";

/* 회원아이디/비밀번호 찾기 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_MF"]["MF_TOP_IMG"]			= "S_MEMBER_FINDIDPWD_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_MF"]["MF_TOP_HTML"]			= "S_MEMBER_FINDIDPWD_TOP_HTML";

/* 회원가입 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_MI"]["MI_TOP_IMG"]			= "S_MEMBER_JOINFORM_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_MI"]["MI_TOP_HTML"]			= "S_MEMBER_JOINFORM_TOP_HTML";

/* 회원가입완료 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_ME"]["ME_TOP_IMG"]			= "S_MEMBER_JOINEND_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_ME"]["ME_TOP_HTML"]			= "S_MEMBER_JOINEND_TOP_HTML";

/** MEMBER 관련 **/

/** ORDER 관련 **/

/* TOP 통합 관리 옵션 설정*/
$_CONF_FIELD_NAME["SKIN_O"]["O_TOP_USE_OP"]			= "S_ORDER_TOP_USE_OP";		// A -> 공통, C -> 각 페이지, N -> 사용 안함
$_CONF_FIELD_NAME["SKIN_O"]["O_TOP_IMG"]			= "S_ORDER_TOP_IMG";		// 공통 이미지

/* 구매내역 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_OB"]["OB_TOP_IMG"]			= "S_ORDER_BUYLIST_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_OB"]["OB_TOP_HTML"]			= "S_ORDER_BUYLIST_TOP_HTML";

/* 장바구니(회원) TOP 설정 */
$_CONF_FIELD_NAME["SKIN_OC"]["OC_TOP_IMG"]			= "S_ORDER_CARTMYLIST_IMG";
$_CONF_FIELD_NAME["SKIN_OC"]["OC_TOP_HTML"]			= "S_ORDER_CARTMYLIST_HTML";

/* 담아둔상품 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_OW"]["OW_TOP_IMG"]			= "S_ORDER_WISHMYLIST_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_OW"]["OW_TOP_HTML"]			= "S_ORDER_WISHMYLIST_TOP_HTML";

/* 포인트관리 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_OP"]["OP_TOP_IMG"]			= "S_ORDER_POINTLIST_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_OP"]["OP_TOP_HTML"]			= "S_ORDER_POINTLIST_TOP_HTML";

/* 쿠폰관리 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_OO"]["OO_TOP_IMG"]			= "S_ORDER_COUPONLIST_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_OO"]["OO_TOP_HTML"]			= "S_ORDER_COUPONLIST_TOP_HTML";

/* 장바구니 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_ON"]["ON_TOP_IMG"]			= "S_ORDER_CART_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_ON"]["ON_TOP_HTML"]			= "S_ORDER_CART_TOP_HTML";

/* 상품주문 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_OD"]["OD_TOP_IMG"]			= "S_ORDER_ORDER_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_OD"]["OD_TOP_HTML"]			= "S_ORDER_ORDER_TOP_HTML";

/* 상품주문 완료 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_OE"]["OE_TOP_IMG"]			= "S_ORDER_ORDEREND_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_OE"]["OE_TOP_HTML"]			= "S_ORDER_ORDEREND_TOP_HTML";

/* 구매내역 상세 상세 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_OA"]["OA_TOP_IMG"]			= "S_ORDER_BUYVIEW_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_OA"]["OA_TOP_HTML"]			= "S_ORDER_BUYVIEW_TOP_HTML";

/* 회원 정보 변경 TOP 설정 */
$_CONF_FIELD_NAME["SKIN_OM"]["OM_TOP_IMG"]			= "S_ORDER_MYINFO_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_OM"]["OM_TOP_HTML"]			= "S_ORDER_MYINFO_TOP_HTML";

/* 구매내역(비회원) TOP 설정 */
$_CONF_FIELD_NAME["SKIN_OG"]["OG_TOP_IMG"]			= "S_ORDER_BUYNONLIST_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_OG"]["OG_TOP_HTML"]			= "S_ORDER_BUYNONLIST_TOP_HTML";

/* 구매내역 상세(비회원) TOP 설정 */
$_CONF_FIELD_NAME["SKIN_OH"]["OH_TOP_IMG"]			= "S_ORDER_BUYNONVIEW_TOP_IMG";
$_CONF_FIELD_NAME["SKIN_OH"]["OH_TOP_HTML"]			= "S_ORDER_BUYNONVIEW_TOP_HTML";

/** ORDER 관련 **/

/** 퀵 메뉴 **/
$_CONF_FIELD_NAME["SKIN_EQ"]["EQ_QUICK_MENU_USE_1"]	= "S_QUICK_MENU_USE_1";
$_CONF_FIELD_NAME["SKIN_EQ"]["EQ_QUICK_MENU_SPE_1"]	= "S_QUICK_MENU_SPE_1";
$_CONF_FIELD_NAME["SKIN_EQ"]["EQ_QUICK_MENU_TOP_1"]	= "S_QUICK_MENU_TOP_1";
$_CONF_FIELD_NAME["SKIN_EQ"]["EQ_QUICK_MENU_LEF_1"]	= "S_QUICK_MENU_LEF_1";
$_CONF_FIELD_NAME["SKIN_EQ"]["EQ_QUICK_MENU_LIST_CNT_1"]	= "S_QUICK_MENU_LIST_CNT_1";
$_CONF_FIELD_NAME["SKIN_EQ"]["EQ_QUICK_MENU_PIMG_SIZ_1"]	= "S_QUICK_MENU_PIMG_SIZ_1";
$_CONF_FIELD_NAME["SKIN_EQ"]["EQ_QUICK_MENU_EFFECT_1"]		= "S_QUICK_MENU_EFFECT_1";
$_CONF_FIELD_NAME["SKIN_EQ"]["EQ_QUICK_MENU_ALIGN_1"]		= "S_QUICK_MENU_ALIGN_1";


$_CONF_FIELD_NAME["SKIN_EQ"]["EQ_QUICK_MENU_USE_2"]	= "S_QUICK_MENU_USE_2";
$_CONF_FIELD_NAME["SKIN_EQ"]["EQ_QUICK_MENU_ACT_2"]	= "S_QUICK_MENU_ACT_2";
$_CONF_FIELD_NAME["SKIN_EQ"]["EQ_QUICK_MENU_SPE_2"]	= "S_QUICK_MENU_SPE_2";
$_CONF_FIELD_NAME["SKIN_EQ"]["EQ_QUICK_MENU_TOP_2"]	= "S_QUICK_MENU_TOP_2";
$_CONF_FIELD_NAME["SKIN_EQ"]["EQ_QUICK_MENU_LEF_2"]	= "S_QUICK_MENU_LEF_2";
/** 퀵 메뉴 **/
