<?
	$S_QUICK_MENU_USE_1		= "Y";
	$S_QUICK_MENU_SPE_1		= "250";
	$S_QUICK_MENU_TOP_1		= "115";
	$S_QUICK_MENU_LEF_1		= "550";
	$S_QUICK_MENU_LIST_CNT_1		= "5";
	$S_QUICK_MENU_PIMG_SIZ_1		= "60*60";
	$S_QUICK_MENU_EFFECT_1		= "A";
	$S_QUICK_MENU_ALIGN_1		= "right";
?>
