<?	
	DEFINE("TBL_ADMIN_MGR"		,"ADMIN_MGR"		);	//관리자관리
	DEFINE("TBL_MENU_MGR"		,"MENU_MGR"			);	//관리자메뉴관리
	DEFINE("TBL_ADMIN_MENU"		,"ADMIN_MENU"		);	//관리자메뉴관리
	
	DEFINE("TBL_COMM_CODE"		,"COMM_CODE"		);		//공통코드
	DEFINE("TBL_COMM_GRP"		,"COMM_GRP"			);		//공통코드그룹관리
	DEFINE("TBL_COMM_FILE"		,"COMM_FILE"		);		//첨부파일관리

	DEFINE("TBL_COMM_VIEW"		,"V_COMM_CODE_LIST"	);		//공통코드(VIEW)

	DEFINE("TBL_SITE_MGR"		,"SITE_MGR"			);		//사이트기본정보
	DEFINE("TBL_SITE_INFO"		,"SITE_INFO"		);		//사이트기본정보(NEW)
	DEFINE("TBL_SITE_TEXT"		,"SITE_TEXT"		);		//사이트기본정보(NEW)
	DEFINE("TBL_SITE_CUR"		,"SITE_CUR"			);		//통화관리
 	DEFINE("TBL_SITE_EVENT"		,"SITE_EVENT"		);		//사이트할인설정

	DEFINE("TBL_CATE_MGR"		,"CATE_MGR"			);		//상품카테고리
	DEFINE("TBL_CATE_LNG"		,"CATE_LNG"			);		//상품카테고리(언어)
	DEFINE("TBL_SITE_COMM"		,"SITE_COMM"		);		//공통관리

	DEFINE("TBL_CONTENT"		,"CONTENT"			);		//컨텐츠 관리
	DEFINE("TBL_DESIGNEDIT"		,"DESIGN_EDIT"		);		//페이지 직접 편집
	
	DEFINE("TBL_DESIGN_SET"					,"DESIGN_SET ");						//디자인 셋팅관리(추가:2011.11.13)
	DEFINE("TBL_DESIGN_HTML_SET"			,"DESIGN_HTML_SET ");					//디자인 HTML셋팅관리(추가:2011.11.13)
	DEFINE("TBL_DESIGN_SLIDER_BANNER"		,"DESIGN_SLIDER_BANNER ");				//움직이는 베너(추가:2012.11.13)
	DEFINE("TBL_DESIGN_SLIDER_BANNER_IMG"	,"DESIGN_SLIDER_BANNER_IMG ");			//움직이는 베너(추가:2012.11.13)

	DEFINE("TBL_SCRAPING_MGR"				,"SCRAPING_MGR"					);	//상품관리(스크랩핑)
	DEFINE("TBL_SCRAPING_PAGE"				,"SCRAPING_PAGE"					);	//상품관리-리스트(스크랩핑)
	DEFINE("TBL_PRODUCT_MGR_TEMP"			,"PRODUCT_MGR_TEMP"			);	//상품관리-리스트(스크랩핑)
	DEFINE("TBL_PRODUCT_IMG_TEMP"			,"PRODUCT_IMG_TEMP"			);	//상품관리-이미지 리스트(스크랩핑)
	DEFINE("TBL_PRODUCT_OPT_TEMP"			,"PRODUCT_OPT_TEMP"			);	//상품관리-옵션 리스트(스크랩핑)	
	DEFINE("TBL_PRODUCT_ITEM_TEMP"			,"PRODUCT_ITEM_TEMP"			);	//상품관리-아이템 리스트(스크랩핑)	


	DEFINE("TBL_PRODUCT_MGR"		,"PRODUCT_MGR"		);	//상품관리
	DEFINE("TBL_PRODUCT_IMG"		,"PRODUCT_IMG"		);	//상품이미지
	DEFINE("VIEW_PRODUCT_ICON"		,"PRODUCT_ICON_VIEW");	//상품아이콘(VIEW)
	DEFINE("TBL_PRODUCT_ITEM"		,"PRODUCT_ITEM");		//상품항목관리
	DEFINE("TBL_PRODUCT_OPT"		,"PRODUCT_OPT");		//상품옵션관리
	DEFINE("TBL_PRODUCT_OPT_ATTR"	,"PRODUCT_OPT_ATTR");	//상품옵션속성관리
	DEFINE("TBL_PRODUCT_ADD_OPT"	,"PRODUCT_ADD_OPT");	//상품추가옵션관리
	DEFINE("TBL_PRODUCT_ICON"		,"PRODUCT_ICON");		//상품아이콘

	DEFINE("TBL_PRODUCT_INFO_LNG"			,"PRODUCT_INFO_");		//상품정보
	DEFINE("TBL_PRODUCT_ITEM_LNG"			,"PRODUCT_ITEM_");		//상품항목관리
	DEFINE("TBL_PRODUCT_OPT_LNG"			,"PRODUCT_OPT_");		//상품옵션관리
	DEFINE("TBL_PRODUCT_OPT_ATTR_LNG"		,"PRODUCT_OPT_ATTR_");	//상품옵션속성관리
	DEFINE("TBL_PRODUCT_ADD_OPT_LNG"		,"PRODUCT_ADD_OPT_");	//상품추가옵션관리
	

	DEFINE("TBL_MEMBER_GROUP"		,"MEMBER_GROUP_MGR");	//회원그룹관리
	DEFINE("TBL_MEMBER_JOIN"		,"MEMBER_JOIN_MGR");	//회원가입관리
	DEFINE("TBL_MEMBER_JOIN_ITEM"	,"MEMBER_JOIN_ITEM");	//회원가입항목관리
	DEFINE("TBL_MEMBER_MGR"			,"MEMBER_MGR");			//회원관리
	DEFINE("TBL_MEMBER_PAPER"		,"MEMBER_PAPER");		//회원족지관리
	DEFINE("TBL_MEMBER_ADD"			,"MEMBER_ADD");		//회원추가항목관리
	DEFINE("TBL_MEMBER_ADDR"		,"MEMBER_ADDR");		//회원주소록관리	
	DEFINE("TBL_MEMBER_FAMILY"		,"MEMBER_FAMILY");		//회원가족관리	

	DEFINE("TBL_MEMBER_CATE"		,"MEMBER_CATE");		//회원소속관리
	DEFINE("TBL_MEMBER_CATE_MGR"	,"MEMBER_CATE_MGR");	//소속관리
	


	DEFINE("TBL_BOARD_MGR"			,"BOARD_MGR");			//게시판관리
	DEFINE("TBL_BOARD_GROUP"		,"BOARD_GROUP");		//게시판그룹관리

	DEFINE("TBL_ZIP"				,"ZIPCODE"			);	//우편번호
	DEFINE("TBL_POPUP"				,"POPUP"			);	//팝업
	DEFINE("TBL_BANNER"				,"BANNER"			);	//배너
	DEFINE("TBL_ADVERTISE"			,"ADVERTISE"		);	//배너

	DEFINE("TBL_COM_VIEW"			,"V_COMM_CODE_LIST"	);	//공통코드 VIEW

	DEFINE("TBL_ORDER_MGR"			,"ORDER_MGR"		);	//주문정보
	DEFINE("TBL_ORDER_SETTLE"		,"ORDER_SETTLE"		);	//주문정보(결제)

	DEFINE("TBL_ORDER_CART"			,"ORDER_CART"		);	//장바구니(주문)
	DEFINE("TBL_ORDER_CART_ADD"		,"ORDER_CART_ADD"	);	//장바구니(주문)

	DEFINE("TBL_ORDER_HAND_ADDR"		,"ORDER_HAND_ADDR"			);	//주문정보
	DEFINE("TBL_ORDER_HAND_ADDR_GRP"	,"ORDER_HAND_ADDR_GRP"		);	//주문정보
	DEFINE("TBL_ORDER_SELF_MEMBER_INFO"	,"ORDER_SELF_MEMBER_INFO"	);	//수기등록 - 주문자, 수령자 정보
	DEFINE("TBL_ORDER_SELF_PRODUCT"		,"ORDER_SELF_PRODUCT"		);	//수기등록 - 주문상품정보

	DEFINE("TBL_ORDER_PERIOD"		,"ORDER_PERIOD"		);	//주문후 사용기간내역
	DEFINE("TBL_ORDER_AUDIT"		,"ORDER_AUDIT"		);	//주문후 발행코드

	
	DEFINE("TBL_PRODUCT_BASKET"		,"PRODUCT_BASKET"	);	//장바구니(주문전)
	DEFINE("TBL_PRODUCT_BASKET_ADD"	,"PRODUCT_BASKET_ADD");	//장바구니(주문전)

	DEFINE("TBL_PRODUCT_WISH"		,"PRODUCT_WISH"		);	//위시리스트(주문전)
	DEFINE("TBL_PRODUCT_WISH_ADD"	,"PRODUCT_WISH_ADD"	);	//위시리스트_추가옵션(주문전)

	DEFINE("TBL_PRODUCT_GRP"		,"PRODUCT_GROUP"	);	//관심상품관리
	DEFINE("TBL_PRODUCT_BRAND"		,"PRODUCT_BRAND"	);	//상품브랜드관리
	DEFINE("TBL_PRODUCT_BRAND_LNG"	,"PRODUCT_BRAND_LNG");	//상품브랜드관리 다국어

	DEFINE("TBL_POINT_MGR"			,"POINT_MGR"		);	//포인트관리

	DEFINE("TBL_EMAIL_MGR"			,"EMAIL_MGR"		);	//자동메일관리
	DEFINE("TBL_ICON_MGR"			,"ICON_MGR"			);	//아이콘(상품DISPLAY)
	DEFINE("TBL_SHIPPING"			,"SHIPPING_MGR"		);	//상품(배송)
	DEFINE("TBL_COUNTRY"			,"COUNTRY_MGR"		);	//국가
	DEFINE("TBL_COUNTRY_IP"			,"COUNTRY_IP"		);	//나라별 IP대역
	DEFINE("TBL_COUNTRY_ZONE"		,"COUNTRY_ZONE"		);	//나라별 ZONE
	DEFINE("TBL_COUNTRY_STATE"		,"COUNTRY_STATE"	);	//나라별 주

	DEFINE("TBL_POST_MAIL"			,"POST_MAIL"		);	//전체메일발송관리
	DEFINE("TBL_POST_MAIL_LOG"		,"POST_MAIL_LOG"	);	//전체메일발송로그
	DEFINE("TBL_POST_SMS"			,"POST_SMS"			);	//전체문자발송관리
	DEFINE("TBL_POST_SMS_LOG"		,"POST_SMS_LOG"		);	//전체문자발송관리
	DEFINE("TBL_POST_PAPER"			,"POST_PAPER"		);	//전체쪽지발송관리
 
 	DEFINE("TBL_PRODUCT_SHARE"		,"PRODUCT_SHARE"	);	//상품공유카테고리

 	DEFINE("TBL_COUPON_MGR"			,"COUPON_MGR"		);	//쿠폰관리
 	DEFINE("TBL_COUPON_APPLY"		,"COUPON_APPLY"		);	//쿠폰적용상품
 	DEFINE("TBL_COUPON_ISSUE"		,"COUPON_ISSUE"		);	//쿠폰발행관리

 	DEFINE("TBL_GIFT_MGR"			,"CUS_GIFT_MGR"		);	//고객사은품관리
	DEFINE("TBL_GIFT_LNG"			,"CUS_GIFT_LNG"		);	//고객사은품관리(다국어)
	DEFINE("TBL_PRODUCT_GIFT"		,"PRODUCT_GIFT"		);	//고객사은품관리_상품
	DEFINE("TBL_ORDER_GIFT"			,"ORDER_GIFT"		);	//고객사은품관리_주문

	DEFINE("TBL_SHOP_MGR"			,"SHOP_MGR"			);	//입점몰관리
	DEFINE("TBL_SHOP_SITE"			,"SHOP_SITE"		);	//입점몰관리(사이트)
	DEFINE("TBL_SHOP_USER"			,"SHOP_USER"		);	//입점몰관리(사용자)
	DEFINE("TBL_SHOP_ORDER"			,"SHOP_ORDER"		);	//입점몰관리(주문)
	DEFINE("TBL_SHOP_ORDER_CART"	,"SHOP_ORDER_CART"	);	//입점몰관리(주문_상품)
	DEFINE("TBL_SHOP_INFO_LNG"		,"SHOP_INFO_"		);	//입점몰 다국어

	DEFINE("TBL_HISTORY_MGR"		,"HISTORY_MGR"		);	//히스토리관리

	DEFINE("TBL_SEARCH_WORD"		,"SEARCH_WORD"		);	//검색어

	
	DEFINE("TBL_PROD_PLAN"			,"PLAN_MGR"			);	//기획전
	DEFINE("TBL_PROD_PLAN_LNG"		,"PLAN_LNG"			);	//기획전(언어)
	DEFINE("TBL_PRODUCT_PLAN"		,"PRODUCT_PLAN"		);	//기획전상품
	DEFINE("TBL_MEMBER_PROD_LIKE"	,"MEMBER_PROD_LIKE"	);	//회원좋아요상품

	DEFINE("TBL_ORDER_STATUS"		,"ORDER_STATUS"		);	//주문별 상태관리
	DEFINE("TBL_ORDER_CART_STATUS"	,"ORDER_CART_STATUS");	//주문상태별 상태관리

	DEFINE("TBL_PROD_AUCTION"		,"PRODUCT_AUCTION");		//경매상품정보
	DEFINE("TBL_PROD_AUCTION_APPLY"	,"PRODUCT_AUCTION_APPLY");	//경매상품정보

	DEFINE("TBL_MOBILE_API"	,"MOBILE_API");	//모바일 APP


?>