


ALTER TABLE BOARD_UB_DATA ADD COLUMN `UB_LNG` VARCHAR(2) COMMENT '작성 언어' AFTER `UB_BC_NO`;
ALTER TABLE BOARD_UB_EQUI_BOARD ADD COLUMN `UB_LNG` VARCHAR(2) COMMENT '작성 언어' AFTER `UB_BC_NO`;
ALTER TABLE BOARD_UB_EVENT ADD COLUMN `UB_LNG` VARCHAR(2) COMMENT '작성 언어' AFTER `UB_BC_NO`;
ALTER TABLE BOARD_UB_FAQ ADD COLUMN `UB_LNG` VARCHAR(2) COMMENT '작성 언어' AFTER `UB_BC_NO`;
ALTER TABLE BOARD_UB_MY_QNA ADD COLUMN `UB_LNG` VARCHAR(2) COMMENT '작성 언어' AFTER `UB_BC_NO`;
ALTER TABLE BOARD_UB_NOTICE ADD COLUMN `UB_LNG` VARCHAR(2) COMMENT '작성 언어' AFTER `UB_BC_NO`;
ALTER TABLE BOARD_UB_PHOTO ADD COLUMN `UB_LNG` VARCHAR(2) COMMENT '작성 언어' AFTER `UB_BC_NO`;
ALTER TABLE BOARD_UB_PROD_QNA ADD COLUMN `UB_LNG` VARCHAR(2) COMMENT '작성 언어' AFTER `UB_BC_NO`;
ALTER TABLE BOARD_UB_REQ ADD COLUMN `UB_LNG` VARCHAR(2) COMMENT '작성 언어' AFTER `UB_BC_NO`;

UPDATE BOARD_UB_COUNQNA SET UB_LNG = 'KR';
UPDATE BOARD_UB_DATA SET UB_LNG = 'KR';
UPDATE BOARD_UB_EQUI_BOARD SET UB_LNG = 'KR';
UPDATE BOARD_UB_EVENT SET UB_LNG = 'KR';
UPDATE BOARD_UB_FAQ SET UB_LNG = 'KR';
UPDATE BOARD_UB_MY_QNA SET UB_LNG = 'KR';
UPDATE BOARD_UB_NOTICE SET UB_LNG = 'KR';
UPDATE BOARD_UB_PHOTO SET UB_LNG = 'KR';
UPDATE BOARD_UB_PROD_QNA SET UB_LNG = 'KR';
UPDATE BOARD_UB_REQ SET UB_LNG = 'KR';


## 2013.04.28 -- 내영(모바일) 컬럼 추가

ALTER TABLE BOARD_UB_NOTICE ADD COLUMN `UB_TEXT_MOBILE` TEXT COMMENT '내용(모바일)' AFTER `UB_TEXT`;


## 2013.04.30 -- 추가 컬럼 정리
ALTER TABLE `BOARD_UB_NOTICE` ADD COLUMN `UB_TEXT_MOBILE` TEXT COMMENT '내용(모바일)' AFTER `UB_TEXT`;
ALTER TABLE `BOARD_UB_NOTICE` ADD COLUMN `UB_LNG` VARCHAR(2) COMMENT '작성 언어' AFTER `UB_BC_NO`;
ALTER TABLE `BOARD_UB_NOTICE` ADD COLUMN `UB_PT_NO` BIGINT COMMENT '이벤트-포인트 번호' AFTER `UB_ANS_STEP`;
ALTER TABLE `BOARD_UB_NOTICE` ADD COLUMN `UB_CI_NO` BIGINT COMMENT '이벤트-쿠폰 번호' AFTER `UB_PT_NO`;
ALTER TABLE `BOARD_UB_NOTICE` ADD COLUMN `UB_WINNER` VARCHAR(1) COMMENT '이벤트-담청자' AFTER `UB_CI_NO`;
ALTER TABLE `BOARD_UB_NOTICE` ADD COLUMN `UB_P_CODE` VARCHAR(20) COMMENT '상품-코드' AFTER `UB_WINNER`;
ALTER TABLE `BOARD_UB_NOTICE` ADD COLUMN `UB_P_GRADE` SMALLINT COMMENT '상품-평점' AFTER `UB_P_CODE`;
ALTER TABLE `BOARD_UB_NOTICE` ADD COLUMN `UB_URL` VARCHAR(200) COMMENT '웹주' AFTER `UB_MAIL`;
