ALTER TABLE BOARD_CM_PHOTO ADD COLUMN `CM_ANS_NO` BIGINT COMMENT '계층형-최상위글 번호' AFTER `CM_READ`;
ALTER TABLE BOARD_CM_PHOTO ADD COLUMN `CM_ANS_STEP` VARCHAR(100) COMMENT '계층형-답변모양' AFTER `CM_ANS_NO`;


