<?php
## 커뮤니티 기본정보(BOARD_INFO_MGR) 명칭 설정
$G_BOARD_INFO_NAME['B_BG_NO'] = "커뮤니티 그룹 번호";
$G_BOARD_INFO_NAME['B_KIND_SKIN'] = "게시판 종류(종류_스킨)";
$G_BOARD_INFO_NAME['BI_START_MODE'] = "커뮤니티 시작 페이지(list,view,write)";
$G_BOARD_INFO_NAME['BI_ADMIN_NICKNAME'] = "커뮤니티 관리자 명칭";
$G_BOARD_INFO_NAME['BI_COMMENT_USE'] = "커뮤니티 코멘트 사용(사용=Y, 모든회원/비회원=A, 회원전용=M)";
$G_BOARD_INFO_NAME['BI_DATALIST_USE'] = "커뮤니티 리스트 사용(사용=Y, 모든회원/비회원=A, 회원전용=M)";
$G_BOARD_INFO_NAME['BI_COLUMN_DEFAULT'] = "세로줄 수";
$G_BOARD_INFO_NAME['BI_LIST_DEFAULT'] = "리스트 수";
$G_BOARD_INFO_NAME['BI_PAGE_DEFAULT'] = "페이지 수";
$G_BOARD_INFO_NAME['BI_DATALIST_ORDERBY'] = "리스트 정렬 설정(등록날짜오름차순, 등록날짜내림차순...)";
$G_BOARD_INFO_NAME['BI_DATALIST_FIELD_USE_0'] = "커뮤니티 리스트 목록 설정(번호)";
$G_BOARD_INFO_NAME['BI_DATALIST_FIELD_USE_1'] = "커뮤니티 리스트 목록 설정(작성자)";
$G_BOARD_INFO_NAME['BI_DATALIST_FIELD_USE_2'] = "커뮤니티 리스트 목록 설정(등록일)";
$G_BOARD_INFO_NAME['BI_DATALIST_FIELD_USE_3'] = "커뮤니티 리스트 목록 설정(조회수)";
$G_BOARD_INFO_NAME['BI_DATALIST_FIELD_USE_4'] = "커뮤니티 리스트 목록 설정(점수)";
$G_BOARD_INFO_NAME['BI_DATALIST_FIELD_USE_5'] = "커뮤니티 리스트 목록 설정(카테고리)";
$G_BOARD_INFO_NAME['BI_DATALIST_WRITER_SHOW_0'] = "커뮤니티 리스트 작성자 표시 방법(성명)";
$G_BOARD_INFO_NAME['BI_DATALIST_WRITER_SHOW_1'] = "커뮤니티 리스트 작성자 표시 방법(아이디)";
$G_BOARD_INFO_NAME['BI_DATALIST_WRITER_SHOW_2'] = "커뮤니티 리스트 작성자 표시 방법(닉네임)";
$G_BOARD_INFO_NAME['BI_DATALIST_WRITER_HIDDEN'] = "커뮤니티 리스트 작성자 부분 숨김(갯수)";
$G_BOARD_INFO_NAME['BI_DATAVIEW_USE'] = "커뮤니티 보기 사용(사용=Y, 모든회원/비회원=A, 회원전용=M)";
$G_BOARD_INFO_NAME['BI_DATAVIEW_TWITTER_USE'] = "트위터 사용";
$G_BOARD_INFO_NAME['BI_DATAVIEW_FACEBOOK_USE'] = "페이스북 사용";
$G_BOARD_INFO_NAME['BI_DATAVIEW_M2DAY_USE'] = "미투데이";
$G_BOARD_INFO_NAME['BI_DATAWRITE_USE'] = "커뮤니티 쓰기/수정 사용(사용=Y, 모든회원/비회원=A, 회원전용=M)";
$G_BOARD_INFO_NAME['BI_DATAWRITE_NOTICE_USE'] = "공지글 사용(사용=Y, 사용안함=N)";
$G_BOARD_INFO_NAME['BI_DATAWRITE_LOCK_USE'] = "비밀글 사용(사용자선택=C.무조건=E,사용안함=N or '')";
$G_BOARD_INFO_NAME['BI_DATAWRITE_FORM'] = "글쓰기 폼(텍스트폼=textWrite, 에디터폼=editWrite)";
$G_BOARD_INFO_NAME['BI_DATAWRITE_ICON_USE'] = "아이콘(사용=Y, 사용안함=N)";
$G_BOARD_INFO_NAME['BI_DATAWRITE_END_MOVE'] = "글쓰기 완료 후, 이동경로(목록화면, 글쓰기화면, 상세보기화면)";
$G_BOARD_INFO_NAME['BI_DATADELETE_USE'] = "커뮤니티 삭제/기타 사용(사용=Y, 모든회원/비회원=A, 회원전용=M)";
$G_BOARD_INFO_NAME['BI_DATAMODIFY_USE'] = "커뮤니티 수정 사용(사용=Y, 모든회원/비회원=A, 회원전용=M)";
$G_BOARD_INFO_NAME['BI_ATTACHEDFILE_USE'] = "커뮤니티 첨부파일 사용(사용=1/2/3/4..., 사용안함=0)";
$G_BOARD_INFO_NAME['BI_ATTACHEDFILE_NAME_0'] = "커뮤니티 첨부파일 이름1";
$G_BOARD_INFO_NAME['BI_ATTACHEDFILE_NAME_1'] = "커뮤니티 첨부파일 이름2";
$G_BOARD_INFO_NAME['BI_ATTACHEDFILE_NAME_2'] = "커뮤니티 첨부파일 이름3";
$G_BOARD_INFO_NAME['BI_ATTACHEDFILE_NAME_3'] = "커뮤니티 첨부파일 이름4";
$G_BOARD_INFO_NAME['BI_ATTACHEDFILE_NAME_4'] = "커뮤니티 첨부파일 이름5";
$G_BOARD_INFO_NAME['BI_ATTACHEDFILE_KEY_0'] = "커뮤니티 첨부파일 키1(file, image, movie..)";
$G_BOARD_INFO_NAME['BI_ATTACHEDFILE_KEY_1'] = "커뮤니티 첨부파일 키2(file, image, movie..)";
$G_BOARD_INFO_NAME['BI_ATTACHEDFILE_KEY_2'] = "커뮤니티 첨부파일 키3(file, image, movie..)";
$G_BOARD_INFO_NAME['BI_ATTACHEDFILE_KEY_3'] = "커뮤니티 첨부파일 키4(file, image, movie..)";
$G_BOARD_INFO_NAME['BI_ATTACHEDFILE_KEY_4'] = "커뮤니티 첨부파일 키5(file, image, movie..)";
$G_BOARD_INFO_NAME['BI_USERFIELD_FIELD_USE'] = "커뮤니티 추가필드 필드 사용(사용=Y 사용안함=N)";
$G_BOARD_INFO_NAME['BI_USERFIELD_NAME'] = "커뮤니티 추가필드 이름";
$G_BOARD_INFO_NAME['BI_USERFIELD_SORT'] = "커뮤니티 추가필드 정렬";
$G_BOARD_INFO_NAME['BI_DATAANSWER_USE'] = "커뮤니티 답변 사용(사용=Y, 모든회원/비회원=A, 회원전용=M, 사용안함=N)";
$G_BOARD_INFO_NAME['BI_DATALIST_TITLE_LEN'] = "커뮤니티 리스트 타이틀 자리수";
$G_BOARD_INFO_NAME['BI_DATAVIEW_NEXTPRVE_USE'] = "커뮤니티 보기에서 다음/이전 리스트 사용(사용=Y, 사용안함=N)";
$G_BOARD_INFO_NAME['BI_ADMIN_MAIN_SHOW'] = "커뮤니티 관리자 메인화면 표시 여부(사용=Y, 사용안함=N)";
$G_BOARD_INFO_NAME['BI_ADMIN_MAIN_SORT'] = "커뮤니티 관리자 메인화면 순위(정렬)";
$G_BOARD_INFO_NAME['BI_SMS_USE'] = "SMS 사용 유무";
$G_BOARD_INFO_NAME['BI_SMS_HP_LIST'] = "받는사람 연락처 리스트(최대5개)";
$G_BOARD_INFO_NAME['BI_SMS_TEXT'] = "SMS 문자 내용";
$G_BOARD_INFO_NAME['BI_DATALIST_MEMBER_AUTH'] = "목록권한 회원 그룹 리스트";

## 카테고리 옵션
$G_BOARD_INFO_NAME['BI_CATEGORY_USE'] = "카테고리 사용유무";
$G_BOARD_INFO_NAME['BI_CATEGORY_SKIN'] = "카테고리 노출 방식";
$G_BOARD_INFO_NAME['BI_CATEGORY_LIST_USE'] = "카테고리 리스트 화면 상단에 카테고리 사용";

## 추가필드
$G_BOARD_INFO_NAME['BI_USERFIELD_USE'] = "추가필드 사용 유무";
$G_BOARD_INFO_NAME['BI_AD_PHONE1_KIND'] = "연락처 필드 종류";
$G_BOARD_INFO_NAME['BI_AD_PHONE1_NAME'] = "연락처 필드 이름";
$G_BOARD_INFO_NAME['BI_AD_PHONE1_SORT'] = "연락처 필드 정렬";
$G_BOARD_INFO_NAME['BI_AD_PHONE1_USE'] = "연락처 필드 사용유무";
$G_BOARD_INFO_NAME['BI_AD_PHONE1_ESSENTIAL'] = "연락처 필드 필수입력 받음";
$G_BOARD_INFO_NAME['BI_AD_PHONE1_ONLYADMIN'] = "연락처 필드 관리자 전용";
$G_BOARD_INFO_NAME['BI_AD_PHONE2_KIND'] = "연락처 필드 종류";
$G_BOARD_INFO_NAME['BI_AD_PHONE2_NAME'] = "연락처 필드 이름";
$G_BOARD_INFO_NAME['BI_AD_PHONE2_SORT'] = "연락처 필드 정렬";
$G_BOARD_INFO_NAME['BI_AD_PHONE2_USE'] = "연락처 필드 사용유무";
$G_BOARD_INFO_NAME['BI_AD_PHONE2_ESSENTIAL'] = "연락처 필드 필수입력 받음";
$G_BOARD_INFO_NAME['BI_AD_PHONE2_ONLYADMIN'] = "연락처 필드 관리자 전용";
$G_BOARD_INFO_NAME['BI_AD_PHONE3_KIND'] = "연락처 필드 종류";
$G_BOARD_INFO_NAME['BI_AD_PHONE3_NAME'] = "연락처 필드 이름";
$G_BOARD_INFO_NAME['BI_AD_PHONE3_SORT'] = "연락처 필드 정렬";
$G_BOARD_INFO_NAME['BI_AD_PHONE3_USE'] = "연락처 필드 사용유무";
$G_BOARD_INFO_NAME['BI_AD_PHONE3_ESSENTIAL'] = "연락처 필드 필수입력 받음";
$G_BOARD_INFO_NAME['BI_AD_PHONE3_ONLYADMIN'] = "연락처 필드 관리자 전용";
$G_BOARD_INFO_NAME['BI_AD_ZIP_KIND'] = "우편번호 필드 종류";
$G_BOARD_INFO_NAME['BI_AD_ZIP_NAME'] = "우편번호 필드 이름";
$G_BOARD_INFO_NAME['BI_AD_ZIP_SORT'] = "우편번호 필드 정렬";
$G_BOARD_INFO_NAME['BI_AD_ZIP_USE'] = "우편번호 필드 사용유무";
$G_BOARD_INFO_NAME['BI_AD_ZIP_ESSENTIAL'] = "우편번호 필드 필수입력 받음";
$G_BOARD_INFO_NAME['BI_AD_ZIP_ONLYADMIN'] = "우편번호 필드 관리자 전용";
$G_BOARD_INFO_NAME['BI_AD_ADDR1_KIND'] = "주소1 필드 종류";
$G_BOARD_INFO_NAME['BI_AD_ADDR1_NAME'] = "주소1 필드 이름";
$G_BOARD_INFO_NAME['BI_AD_ADDR1_SORT'] = "주소1 필드 정렬";
$G_BOARD_INFO_NAME['BI_AD_ADDR1_USE'] = "주소1 필드 사용유무";
$G_BOARD_INFO_NAME['BI_AD_ADDR1_ESSENTIAL'] = "주소1 필드 필수입력 받음";
$G_BOARD_INFO_NAME['BI_AD_ADDR1_ONLYADMIN'] = "주소1 필드 관리자 전용";
$G_BOARD_INFO_NAME['BI_AD_ADDR2_KIND'] = "주소2 필드 종류";
$G_BOARD_INFO_NAME['BI_AD_ADDR2_NAME'] = "주소2 필드 이름";
$G_BOARD_INFO_NAME['BI_AD_ADDR2_SORT'] = "주소2 필드 정렬";
$G_BOARD_INFO_NAME['BI_AD_ADDR2_USE'] = "주소2 필드 사용유무";
$G_BOARD_INFO_NAME['BI_AD_ADDR2_ESSENTIAL'] = "주소2 필드 필수입력 받음";
$G_BOARD_INFO_NAME['BI_AD_ADDR2_ONLYADMIN'] = "주소2 필드 관리자 전용";
$G_BOARD_INFO_NAME['BI_AD_COMPANY_KIND'] = "회사명 필드 종류";
$G_BOARD_INFO_NAME['BI_AD_COMPANY_NAME'] = "회사명 필드 이름";
$G_BOARD_INFO_NAME['BI_AD_COMPANY_SORT'] = "회사명 필드 정렬";
$G_BOARD_INFO_NAME['BI_AD_COMPANY_USE'] = "회사명 필드 사용유무";
$G_BOARD_INFO_NAME['BI_AD_COMPANY_KIND_DATA'] = "회사명 필드 데이터";
$G_BOARD_INFO_NAME['BI_AD_COMPANY_KIND_DEFAULT'] = "회사명 필드 기본값";
$G_BOARD_INFO_NAME['BI_AD_COMPANY_ESSENTIAL'] = "회사명 필드 필수입력 받음";
$G_BOARD_INFO_NAME['BI_AD_COMPANY_ONLYADMIN'] = "회사명 필드 관리자 전용";

for($i=1;$i<=20;$i++):
$G_BOARD_INFO_NAME["BI_AD_TEMP{$i}_KIND"] = "임시필드 종류";
$G_BOARD_INFO_NAME["BI_AD_TEMP{$i}_NAME"] = "임시필드 이름";
$G_BOARD_INFO_NAME["BI_AD_TEMP{$i}_SORT"] = "임시필드 정렬";
$G_BOARD_INFO_NAME["BI_AD_TEMP{$i}_USE"] = "임시필드 사용유무";
$G_BOARD_INFO_NAME["BI_AD_TEMP{$i}_KIND_DATA"] = "임시필드 데이터";
$G_BOARD_INFO_NAME["BI_AD_TEMP{$i}_KIND_DEFAULT"] = "임시필드 기본값";
$G_BOARD_INFO_NAME["BI_AD_TEMP{$i}_ESSENTIAL"] = "임시필드 필수입력 받음";
$G_BOARD_INFO_NAME["BI_AD_TEMP{$i}_ONLYADMIN"] = "임시필드 관리자 전용";
endfor;
