<?php

## 추가 필드 정보
$s										= 0;
$G_USERFIELD_INFO[$s]['comment']		= "연락처1";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_PHONE1";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "30";
$G_USERFIELD_INFO[$s]['kindList']		= "phone";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "연락처2";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_PHONE2";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "30";
$G_USERFIELD_INFO[$s]['kindList']		= "phone";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "연락처3";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_PHONE3";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "30";
$G_USERFIELD_INFO[$s]['kindList']		= "phone";
$s++;
//$G_USERFIELD_INFO[$s]['comment']		= "우편번호";
//$G_USERFIELD_INFO[$s]['columnName']		= "AD_ZIP";
//$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
//$G_USERFIELD_INFO[$s]['columnSize']		= "10";
//$G_USERFIELD_INFO[$s]['kindList']		= "zip";
//$s++;
$G_USERFIELD_INFO[$s]['comment']		= "주소1";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_ADDR1";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "100";
$G_USERFIELD_INFO[$s]['kindList']		= "address";
$s++;
//$G_USERFIELD_INFO[$s]['comment']		= "주소2";
//$G_USERFIELD_INFO[$s]['columnName']	= "AD_ADDR2";
//$G_USERFIELD_INFO[$s]['columnType']	= "varchar";
//$G_USERFIELD_INFO[$s]['columnSize']	= "150";
//$G_USERFIELD_INFO[$s]['kindList']		= "text";
//$s++;
$G_USERFIELD_INFO[$s]['comment']		= "회사명";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_COMPANY";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "100";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드1";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP1";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "50";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드2";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP2";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "50";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드3";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP3";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "50";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드4";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP4";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "50";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드5";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP5";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "200";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드6";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP6";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "200";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드7";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP7";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "200";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드8";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP8";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "200";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드9";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP9";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "500";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드10";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP10";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "500";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드11";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP11";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "500";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드12";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP12";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "500";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드13";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP13";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "10";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드14";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP14";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "10";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드15";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP15";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "10";
$G_USERFIELD_INFO[$s]['kindList']		= "text;select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드16";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP16";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "1";
$G_USERFIELD_INFO[$s]['kindList']		= "select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드17";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP17";
$G_USERFIELD_INFO[$s]['columnType']		= "varchar";
$G_USERFIELD_INFO[$s]['columnSize']		= "1";
$G_USERFIELD_INFO[$s]['kindList']		= "select;radio";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드18";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP18";
$G_USERFIELD_INFO[$s]['columnType']		= "text";
$G_USERFIELD_INFO[$s]['columnSize']		= "";
$G_USERFIELD_INFO[$s]['kindList']		= "textarea;wysiwyg";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드19";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP19";
$G_USERFIELD_INFO[$s]['columnType']		= "text";
$G_USERFIELD_INFO[$s]['columnSize']		= "";
$G_USERFIELD_INFO[$s]['kindList']		= "textarea;wysiwyg";
$s++;
$G_USERFIELD_INFO[$s]['comment']		= "임시필드20";
$G_USERFIELD_INFO[$s]['columnName']		= "AD_TEMP20";
$G_USERFIELD_INFO[$s]['columnType']		= "text";
$G_USERFIELD_INFO[$s]['columnSize']		= "";
$G_USERFIELD_INFO[$s]['kindList']		= "textarea;wysiwyg";
$s++;