<?
$MALL_ADMIN_MENU_VERSION = "1.1"; 
$aryMallAdminLMenu[0][MN_NO]		= "167"; 
$aryMallAdminLMenu[0][MN_NAME_KR]	= "메인화면"; 
$aryMallAdminLMenu[0][MN_NAME_US]	= "Main"; 
$aryMallAdminLMenu[0][MN_NAME_CN]	= "메인화면"; 
$aryMallAdminLMenu[0][MN_URL]		= "./?menuType=main&mode=memberList"; 
$aryMallAdminLMenu[0][MN_USE]		= "Y"; 
$aryMallAdminLMenu[0][MN_ORDER]		= "1"; 
$aryMallAdminLMenu[0][MN_CODE]		= "012"; 
$aryMallAdminLMenu[0][MN_HIGH_01]	= ""; 
$aryMallAdminLMenu[0][MN_HIGH_02]	= ""; 
$aryMallAdminMenu[167][MN_NO]		= "167"; 
$aryMallAdminMenu[167][MN_NAME_KR]	= "메인화면"; 
$aryMallAdminMenu[167][MN_NAME_US]	= "Main"; 
$aryMallAdminMenu[167][MN_NAME_CN]	= "메인화면"; 
$aryMallAdminMenu[167][MN_LEVEL]	= "1"; 
$aryMallAdminMenu[167][MN_URL]		= "./?menuType=main&mode=memberList"; 
$aryMallAdminMenu[167][MN_USE]		= "Y"; 
$aryMallAdminMenu[167][MN_ORDER]	= "1"; 
$aryMallAdminMenu[168][MN_NO]		= "168"; 
$aryMallAdminMenu[168][MN_NAME_KR]	= "메인화면"; 
$aryMallAdminMenu[168][MN_NAME_US]	= "Main"; 
$aryMallAdminMenu[168][MN_NAME_CN]	= "메인화면"; 
$aryMallAdminMenu[168][MN_LEVEL]	= "2"; 
$aryMallAdminMenu[168][MN_URL]		= "./?menuType=main&mode=memberList"; 
$aryMallAdminMenu[168][MN_USE]		= "Y"; 
$aryMallAdminMenu[168][MN_ORDER]	= "1"; 
$aryMallAdminLMenu[1][MN_NO]		= "148"; 
$aryMallAdminLMenu[1][MN_NAME_KR]	= "입점사정보"; 
$aryMallAdminLMenu[1][MN_NAME_US]	= "Seller Information"; 
$aryMallAdminLMenu[1][MN_NAME_CN]	= "卖家信息"; 
$aryMallAdminLMenu[1][MN_URL]		= "./?menuType=seller&mode=shopList"; 
$aryMallAdminLMenu[1][MN_USE]		= "Y"; 
$aryMallAdminLMenu[1][MN_ORDER]		= "2"; 
$aryMallAdminLMenu[1][MN_CODE]		= "011"; 
$aryMallAdminLMenu[1][MN_HIGH_01]	= ""; 
$aryMallAdminLMenu[1][MN_HIGH_02]	= ""; 
$aryMallAdminMenu[148][MN_NO]		= "148"; 
$aryMallAdminMenu[148][MN_NAME_KR]	= "입점사정보"; 
$aryMallAdminMenu[148][MN_NAME_US]	= "Seller Information"; 
$aryMallAdminMenu[148][MN_NAME_CN]	= "卖家信息"; 
$aryMallAdminMenu[148][MN_LEVEL]	= "1"; 
$aryMallAdminMenu[148][MN_URL]		= "./?menuType=seller&mode=shopList"; 
$aryMallAdminMenu[148][MN_USE]		= "Y"; 
$aryMallAdminMenu[148][MN_ORDER]	= "2"; 
$aryMallAdminMenu[149][MN_NO]		= "149"; 
$aryMallAdminMenu[149][MN_NAME_KR]	= "입점사정보"; 
$aryMallAdminMenu[149][MN_NAME_US]	= "Seller Information"; 
$aryMallAdminMenu[149][MN_NAME_CN]	= "卖家信息";
$aryMallAdminMenu[149][MN_LEVEL]	= "2"; 
$aryMallAdminMenu[149][MN_URL]		= "./?menuType=seller&mode=shopList"; 
$aryMallAdminMenu[149][MN_USE]		= "Y"; 
$aryMallAdminMenu[149][MN_ORDER]	= "1"; 
$aryMallAdminMenu[150][MN_NO]		= "150"; 
$aryMallAdminMenu[150][MN_NAME_KR]	= "입점사정보"; 
$aryMallAdminMenu[150][MN_NAME_US]	= "Seller Information"; 
$aryMallAdminMenu[150][MN_NAME_CN]	= "卖家信息";  
$aryMallAdminMenu[150][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[150][MN_URL]		= "./?menuType=seller&mode=shopList"; 
$aryMallAdminMenu[150][MN_USE]		= "Y"; 
$aryMallAdminMenu[150][MN_ORDER]	= "1"; 
$aryMallAdminLMenu[2][MN_NO]		= "3"; 
$aryMallAdminLMenu[2][MN_NAME_KR]	= "회원관리"; 
$aryMallAdminLMenu[2][MN_NAME_US]	= "Member Management"; 
$aryMallAdminLMenu[2][MN_NAME_CN]	= "회원관리"; 
$aryMallAdminLMenu[2][MN_URL]		= "./?menuType=member&mode=memberList"; 
$aryMallAdminLMenu[2][MN_USE]		= "Y"; 
$aryMallAdminLMenu[2][MN_ORDER]		= "4"; 
$aryMallAdminLMenu[2][MN_CODE]		= "003"; 
$aryMallAdminLMenu[2][MN_HIGH_01]	= ""; 
$aryMallAdminLMenu[2][MN_HIGH_02]	= ""; 
$aryMallAdminMenu[3][MN_NO]		= "3"; 
$aryMallAdminMenu[3][MN_NAME_KR]	= "회원관리"; 
$aryMallAdminMenu[3][MN_NAME_US]	= "Member Management"; 
$aryMallAdminMenu[3][MN_NAME_CN]	= "회원관리"; 
$aryMallAdminMenu[3][MN_LEVEL]	= "1"; 
$aryMallAdminMenu[3][MN_URL]		= "./?menuType=member&mode=memberList"; 
$aryMallAdminMenu[3][MN_USE]		= "Y"; 
$aryMallAdminMenu[3][MN_ORDER]	= "4"; 
$aryMallAdminMenu[151][MN_NO]		= "151"; 
$aryMallAdminMenu[151][MN_NAME_KR]	= "쪽지함관리"; 
$aryMallAdminMenu[151][MN_NAME_US]	= "쪽지함관리"; 
$aryMallAdminMenu[151][MN_NAME_CN]	= "쪽지함관리"; 
$aryMallAdminMenu[151][MN_LEVEL]	= "2"; 
$aryMallAdminMenu[151][MN_URL]		= "./?menuType=sendpaper&mode=receivePaperList"; 
$aryMallAdminMenu[151][MN_USE]		= "Y"; 
$aryMallAdminMenu[151][MN_ORDER]	= "5"; 
$aryMallAdminMenu[152][MN_NO]		= "152"; 
$aryMallAdminMenu[152][MN_NAME_KR]	= "받은쪽지"; 
$aryMallAdminMenu[152][MN_NAME_US]	= "받은쪽지"; 
$aryMallAdminMenu[152][MN_NAME_CN]	= "받은쪽지"; 
$aryMallAdminMenu[152][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[152][MN_URL]		= "./?menuType=sendpaper&mode=receivePaperList"; 
$aryMallAdminMenu[152][MN_USE]		= "Y"; 
$aryMallAdminMenu[152][MN_ORDER]	= "1"; 
$aryMallAdminLMenu[3][MN_NO]		= "4"; 
$aryMallAdminLMenu[3][MN_NAME_KR]	= "상품관리"; 
$aryMallAdminLMenu[3][MN_NAME_US]	= "Product Management"; 
$aryMallAdminLMenu[3][MN_NAME_CN]	= "商品管理"; 
$aryMallAdminLMenu[3][MN_URL]		= "./?menuType=product&mode=prodList"; 
$aryMallAdminLMenu[3][MN_USE]		= "Y"; 
$aryMallAdminLMenu[3][MN_ORDER]		= "5"; 
$aryMallAdminLMenu[3][MN_CODE]		= "004"; 
$aryMallAdminLMenu[3][MN_HIGH_01]	= ""; 
$aryMallAdminLMenu[3][MN_HIGH_02]	= ""; 
$aryMallAdminMenu[4][MN_NO]		= "4"; 
$aryMallAdminMenu[4][MN_NAME_KR]	= "상품관리"; 
$aryMallAdminMenu[4][MN_NAME_US]	= "Product Management"; 
$aryMallAdminMenu[4][MN_NAME_CN]	= "商品管理";  
$aryMallAdminMenu[4][MN_LEVEL]	= "1"; 
$aryMallAdminMenu[4][MN_URL]		= "./?menuType=product&mode=prodList"; 
$aryMallAdminMenu[4][MN_USE]		= "Y"; 
$aryMallAdminMenu[4][MN_ORDER]	= "5"; 
$aryMallAdminMenu[34][MN_NO]		= "34"; 
$aryMallAdminMenu[34][MN_NAME_KR]	= "상품관리"; 
$aryMallAdminMenu[34][MN_NAME_US]	= "Product Management"; 
$aryMallAdminMenu[34][MN_NAME_CN]	= "商品管理"; 
$aryMallAdminMenu[34][MN_LEVEL]	= "2"; 
$aryMallAdminMenu[34][MN_URL]		= "./?menuType=product&mode=prodList"; 
$aryMallAdminMenu[34][MN_USE]		= "Y"; 
$aryMallAdminMenu[34][MN_ORDER]	= "1"; 
$aryMallAdminMenu[35][MN_NO]		= "35"; 
$aryMallAdminMenu[35][MN_NAME_KR]	= "판매상품목록"; 
$aryMallAdminMenu[35][MN_NAME_US]	= "Product List"; 
$aryMallAdminMenu[35][MN_NAME_CN]	= "销售商品目录"; 
$aryMallAdminMenu[35][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[35][MN_URL]		= "./?menuType=product&mode=prodList"; 
$aryMallAdminMenu[35][MN_USE]		= "Y"; 
$aryMallAdminMenu[35][MN_ORDER]	= "1"; 
$aryMallAdminMenu[36][MN_NO]		= "36"; 
$aryMallAdminMenu[36][MN_NAME_KR]	= "상품신규등록"; 
$aryMallAdminMenu[36][MN_NAME_US]	= "Product Registration"; 
$aryMallAdminMenu[36][MN_NAME_CN]	= "登录新商品"; 
$aryMallAdminMenu[36][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[36][MN_URL]		= "./?menuType=product&mode=prodWrite"; 
$aryMallAdminMenu[36][MN_USE]		= "Y"; 
$aryMallAdminMenu[36][MN_ORDER]	= "2"; 
$aryMallAdminMenu[37][MN_NO]		= "37"; 
$aryMallAdminMenu[37][MN_NAME_KR]	= "화면출력 및 재고관리"; 
$aryMallAdminMenu[37][MN_NAME_US]	= "Stock Management"; 
$aryMallAdminMenu[37][MN_NAME_CN]	= "商品库存管理"; 
$aryMallAdminMenu[37][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[37][MN_URL]		= "./?menuType=product&mode=prodStockList"; 
$aryMallAdminMenu[37][MN_USE]		= "Y"; 
$aryMallAdminMenu[37][MN_ORDER]	= "3"; 
$aryMallAdminMenu[38][MN_NO]		= "38"; 
$aryMallAdminMenu[38][MN_NAME_KR]	= "상품부가관리"; 
$aryMallAdminMenu[38][MN_NAME_US]	= "Wish List Management"; 
$aryMallAdminMenu[38][MN_NAME_CN]	= "管理相关商品"; 
$aryMallAdminMenu[38][MN_LEVEL]	= "2"; 
$aryMallAdminMenu[38][MN_URL]		= "./?menuType=product&mode=prodDisplay"; 
$aryMallAdminMenu[38][MN_USE]		= "Y"; 
$aryMallAdminMenu[38][MN_ORDER]	= "3"; 
$aryMallAdminMenu[165][MN_NO]		= "165"; 
$aryMallAdminMenu[165][MN_NAME_KR]	= "상품대량등록/수정"; 
$aryMallAdminMenu[165][MN_NAME_US]	= "Register Mass Products"; 
$aryMallAdminMenu[165][MN_NAME_CN]	= "登录大量商品"; 
$aryMallAdminMenu[165][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[165][MN_URL]		= "./?menuType=product&mode=prodAtOneTimeWrite"; 
$aryMallAdminMenu[165][MN_USE]		= "Y"; 
$aryMallAdminMenu[165][MN_ORDER]	= "3"; 
$aryMallAdminMenu[40][MN_NO]		= "40"; 
$aryMallAdminMenu[40][MN_NAME_KR]	= "카테고리관리"; 
$aryMallAdminMenu[40][MN_NAME_US]	= "Category Management"; 
$aryMallAdminMenu[40][MN_NAME_CN]	= "카테고리관리"; 
$aryMallAdminMenu[40][MN_LEVEL]	= "2"; 
$aryMallAdminMenu[40][MN_URL]		= "./?menuType=product&mode=cateList"; 
$aryMallAdminMenu[40][MN_USE]		= "Y"; 
$aryMallAdminMenu[40][MN_ORDER]	= "4"; 
$aryMallAdminMenu[41][MN_NO]		= "41"; 
$aryMallAdminMenu[41][MN_NAME_KR]	= "카테고리관리"; 
$aryMallAdminMenu[41][MN_NAME_US]	= "Category Management"; 
$aryMallAdminMenu[41][MN_NAME_CN]	= "카테고리관리"; 
$aryMallAdminMenu[41][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[41][MN_URL]		= "./?menuType=product&mode=cateList"; 
$aryMallAdminMenu[41][MN_USE]		= "Y"; 
$aryMallAdminMenu[41][MN_ORDER]	= "1"; 
$aryMallAdminLMenu[4][MN_NO]		= "5"; 
$aryMallAdminLMenu[4][MN_NAME_KR]	= "주문관리"; 
$aryMallAdminLMenu[4][MN_NAME_US]	= "Order Management"; 
$aryMallAdminLMenu[4][MN_NAME_CN]	= "订单管理"; 
$aryMallAdminLMenu[4][MN_URL]		= "./?menuType=order&mode=list"; 
$aryMallAdminLMenu[4][MN_USE]		= "Y"; 
$aryMallAdminLMenu[4][MN_ORDER]		= "6"; 
$aryMallAdminLMenu[4][MN_CODE]		= "005"; 
$aryMallAdminLMenu[4][MN_HIGH_01]	= ""; 
$aryMallAdminLMenu[4][MN_HIGH_02]	= ""; 
$aryMallAdminMenu[5][MN_NO]		= "5"; 
$aryMallAdminMenu[5][MN_NAME_KR]	= "주문관리"; 
$aryMallAdminMenu[5][MN_NAME_US]	= "Order Management"; 
$aryMallAdminMenu[5][MN_NAME_CN]	= "订单管理"; 
$aryMallAdminMenu[5][MN_LEVEL]	= "1"; 
$aryMallAdminMenu[5][MN_URL]		= "./?menuType=order&mode=list"; 
$aryMallAdminMenu[5][MN_USE]		= "Y"; 
$aryMallAdminMenu[5][MN_ORDER]	= "6"; 
$aryMallAdminMenu[47][MN_NO]		= "47"; 
$aryMallAdminMenu[47][MN_NAME_KR]	= "주문관리"; 
$aryMallAdminMenu[47][MN_NAME_US]	= "Order Management"; 
$aryMallAdminMenu[47][MN_NAME_CN]	= "订单管理"; 
$aryMallAdminMenu[47][MN_LEVEL]	= "2"; 
$aryMallAdminMenu[47][MN_URL]		= "./?menuType=order&mode=list"; 
$aryMallAdminMenu[47][MN_USE]		= "Y"; 
$aryMallAdminMenu[47][MN_ORDER]	= "1"; 
$aryMallAdminMenu[48][MN_NO]		= "48"; 
$aryMallAdminMenu[48][MN_NAME_KR]	= "주문리스트"; 
$aryMallAdminMenu[48][MN_NAME_US]	= "Order List"; 
$aryMallAdminMenu[48][MN_NAME_CN]	= "订单目录"; 
$aryMallAdminMenu[48][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[48][MN_URL]		= "./?menuType=order&mode=list"; 
$aryMallAdminMenu[48][MN_USE]		= "Y"; 
$aryMallAdminMenu[48][MN_ORDER]	= "1"; 
$aryMallAdminMenu[49][MN_NO]		= "49"; 
$aryMallAdminMenu[49][MN_NAME_KR]	= "입금예정목록"; 
$aryMallAdminMenu[49][MN_NAME_US]	= "Products to be paid List"; 
$aryMallAdminMenu[49][MN_NAME_CN]	= "预计付款目录";  
$aryMallAdminMenu[49][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[49][MN_URL]		= "./?menuType=order&mode=list&searchOrderStatus=J"; 
$aryMallAdminMenu[49][MN_USE]		= "Y"; 
$aryMallAdminMenu[49][MN_ORDER]	= "2"; 
$aryMallAdminMenu[50][MN_NO]		= "50"; 
$aryMallAdminMenu[50][MN_NAME_KR]	= "취소신청목록"; 
$aryMallAdminMenu[50][MN_NAME_US]	= "Products to be canceled List"; 
$aryMallAdminMenu[50][MN_NAME_CN]	= "申请取消目录";  
$aryMallAdminMenu[50][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[50][MN_URL]		= "./?menuType=order&mode=list&searchOrderStatus=C"; 
$aryMallAdminMenu[50][MN_USE]		= "Y"; 
$aryMallAdminMenu[50][MN_ORDER]	= "3"; 
$aryMallAdminMenu[153][MN_NO]		= "153"; 
$aryMallAdminMenu[153][MN_NAME_KR]	= "배송관리"; 
$aryMallAdminMenu[153][MN_NAME_US]	= "Delivery Management"; 
$aryMallAdminMenu[153][MN_NAME_CN]	= "配送管理"; 
$aryMallAdminMenu[153][MN_LEVEL]	= "2"; 
$aryMallAdminMenu[153][MN_URL]		= "./?menuType=order&mode=deliveryFastInput"; 
$aryMallAdminMenu[153][MN_USE]		= "Y"; 
$aryMallAdminMenu[153][MN_ORDER]	= "1"; 
$aryMallAdminMenu[155][MN_NO]		= "155"; 
$aryMallAdminMenu[155][MN_NAME_KR]	= "송장입력목록"; 
$aryMallAdminMenu[155][MN_NAME_US]	= "Invoice input List"; 
$aryMallAdminMenu[155][MN_NAME_CN]	= "物流单号目录";  
$aryMallAdminMenu[155][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[155][MN_URL]		= "./?menuType=order&mode=deliveryList"; 
$aryMallAdminMenu[155][MN_USE]		= "Y"; 
$aryMallAdminMenu[155][MN_ORDER]	= "2"; 
$aryMallAdminMenu[156][MN_NO]		= "156"; 
$aryMallAdminMenu[156][MN_NAME_KR]	= "배송중목록"; 
$aryMallAdminMenu[156][MN_NAME_US]	= "In Delivery List"; 
$aryMallAdminMenu[156][MN_NAME_CN]	= "配送中目录"; 
$aryMallAdminMenu[156][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[156][MN_URL]		= "./?menuType=order&mode=deliveryList&searchOrderStatus=I"; 
$aryMallAdminMenu[156][MN_USE]		= "Y"; 
$aryMallAdminMenu[156][MN_ORDER]	= "3"; 
$aryMallAdminMenu[157][MN_NO]		= "157"; 
$aryMallAdminMenu[157][MN_NAME_KR]	= "배송완료목록"; 
$aryMallAdminMenu[157][MN_NAME_US]	= "Delivery Completed List"; 
$aryMallAdminMenu[157][MN_NAME_CN]	= "完成配送目录";  
$aryMallAdminMenu[157][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[157][MN_URL]		= "./?menuType=order&mode=deliveryList&searchOrderStatus=D"; 
$aryMallAdminMenu[157][MN_USE]		= "Y"; 
$aryMallAdminMenu[157][MN_ORDER]	= "4"; 
$aryMallAdminMenu[158][MN_NO]		= "158"; 
$aryMallAdminMenu[158][MN_NAME_KR]	= "정산관리"; 
$aryMallAdminMenu[158][MN_NAME_US]	= "Balance Management"; 
$aryMallAdminMenu[158][MN_NAME_CN]	= "对账管理"; 
$aryMallAdminMenu[158][MN_LEVEL]	= "2"; 
$aryMallAdminMenu[158][MN_URL]		= "./?menuType=order&mode=accList&searchAccStatus=N"; 
$aryMallAdminMenu[158][MN_USE]		= "Y"; 
$aryMallAdminMenu[158][MN_ORDER]	= "1"; 
$aryMallAdminMenu[54][MN_NO]		= "54"; 
$aryMallAdminMenu[54][MN_NAME_KR]	= "구매확정목록"; 
$aryMallAdminMenu[54][MN_NAME_US]	= "Confirmed Purchase List"; 
$aryMallAdminMenu[54][MN_NAME_CN]	= "确定购买目录"; 
$aryMallAdminMenu[54][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[54][MN_URL]		= "./?menuType=order&mode=list&searchOrderStatus=E"; 
$aryMallAdminMenu[54][MN_USE]		= "Y"; 
$aryMallAdminMenu[54][MN_ORDER]	= "1"; 
$aryMallAdminMenu[159][MN_NO]		= "159"; 
$aryMallAdminMenu[159][MN_NAME_KR]	= "정산예정목록"; 
$aryMallAdminMenu[159][MN_NAME_US]	= "Balance Pending List"; 
$aryMallAdminMenu[159][MN_NAME_CN]	= "预计对账目录"; 
$aryMallAdminMenu[159][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[159][MN_URL]		= "./?menuType=order&mode=accList&searchAccStatus=N"; 
$aryMallAdminMenu[159][MN_USE]		= "Y"; 
$aryMallAdminMenu[159][MN_ORDER]	= "2"; 
$aryMallAdminMenu[160][MN_NO]		= "160"; 
$aryMallAdminMenu[160][MN_NAME_KR]	= "정산완료목록"; 
$aryMallAdminMenu[160][MN_NAME_US]	= "Balance Completed List"; 
$aryMallAdminMenu[160][MN_NAME_CN]	= " 完成对账目录";  
$aryMallAdminMenu[160][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[160][MN_URL]		= "./?menuType=order&mode=accList&searchAccStatus=Y"; 
$aryMallAdminMenu[160][MN_USE]		= "Y"; 
$aryMallAdminMenu[160][MN_ORDER]	= "3"; 
$aryMallAdminMenu[169][MN_NO]		= "169"; 
$aryMallAdminMenu[169][MN_NAME_KR]	= "반품관리"; 
$aryMallAdminMenu[169][MN_NAME_US]	= "Return Management"; 
$aryMallAdminMenu[169][MN_NAME_CN]	= "Return Management";
$aryMallAdminMenu[169][MN_LEVEL]	= "2"; 
$aryMallAdminMenu[169][MN_URL]		= "./?menuType=order&mode=list&searchOrderStatus=R"; 
$aryMallAdminMenu[169][MN_USE]		= "Y"; 
$aryMallAdminMenu[169][MN_ORDER]	= "4"; 
$aryMallAdminMenu[53][MN_NO]		= "53"; 
$aryMallAdminMenu[53][MN_NAME_KR]	= "반품/교환신청목록"; 
$aryMallAdminMenu[53][MN_NAME_US]	= "Return/Exchange Request Management"; 
$aryMallAdminMenu[53][MN_NAME_CN]	= "退货/换货申请目录"; 
$aryMallAdminMenu[53][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[53][MN_URL]		= "./?menuType=order&mode=list&searchOrderStatus=R"; 
$aryMallAdminMenu[53][MN_USE]		= "Y"; 
$aryMallAdminMenu[53][MN_ORDER]	= "1"; 
$aryMallAdminMenu[51][MN_NO]		= "51"; 
$aryMallAdminMenu[51][MN_NAME_KR]	= "환불신청목록"; 
$aryMallAdminMenu[51][MN_NAME_US]	= "Refund Request Management"; 
$aryMallAdminMenu[51][MN_NAME_CN]	= "退款申请目录"; 
$aryMallAdminMenu[51][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[51][MN_URL]		= "./?menuType=order&mode=list&searchOrderStatus=T"; 
$aryMallAdminMenu[51][MN_USE]		= "Y"; 
$aryMallAdminMenu[51][MN_ORDER]	= "6"; 
$aryMallAdminLMenu[6][MN_NO]		= "8"; 
$aryMallAdminLMenu[6][MN_NAME_KR]	= "통계관리"; 
$aryMallAdminLMenu[6][MN_NAME_US]	= "Statistics Management"; 
$aryMallAdminLMenu[6][MN_NAME_CN]	= "统计管理"; 
$aryMallAdminLMenu[6][MN_URL]		= "./?menuType=weblog&mode=visitYear"; 
$aryMallAdminLMenu[6][MN_USE]		= "Y"; 
$aryMallAdminLMenu[6][MN_ORDER]		= "10"; 
$aryMallAdminLMenu[6][MN_CODE]		= "008"; 
$aryMallAdminLMenu[6][MN_HIGH_01]	= ""; 
$aryMallAdminLMenu[6][MN_HIGH_02]	= ""; 
$aryMallAdminMenu[8][MN_NO]		= "8"; 
$aryMallAdminMenu[8][MN_NAME_KR]	= "통계관리"; 
$aryMallAdminMenu[8][MN_NAME_US]	= "Statistics Management"; 
$aryMallAdminMenu[8][MN_NAME_CN]	= "통계관리"; 
$aryMallAdminMenu[8][MN_LEVEL]	= "1"; 
$aryMallAdminMenu[8][MN_URL]		= "./?menuType=weblog&mode=visitYear"; 
$aryMallAdminMenu[8][MN_USE]		= "Y"; 
$aryMallAdminMenu[8][MN_ORDER]	= "10"; 
$aryMallAdminMenu[83][MN_NO]		= "83"; 
$aryMallAdminMenu[83][MN_NAME_KR]	= "매출분석"; 
$aryMallAdminMenu[83][MN_NAME_US]	= "Sales Analysis"; 
$aryMallAdminMenu[83][MN_NAME_CN]	= "销售量分析"; 
$aryMallAdminMenu[83][MN_LEVEL]	= "2"; 
$aryMallAdminMenu[83][MN_URL]		= "./?menuType=weblog&mode=orderDayStatics"; 
$aryMallAdminMenu[83][MN_USE]		= "Y"; 
$aryMallAdminMenu[83][MN_ORDER]	= "2"; 
$aryMallAdminMenu[84][MN_NO]		= "84"; 
$aryMallAdminMenu[84][MN_NAME_KR]	= "일별매출통계"; 
$aryMallAdminMenu[84][MN_NAME_US]	= "Daily Sales Statistics"; 
$aryMallAdminMenu[84][MN_NAME_CN]	= "日销售量统计";  
$aryMallAdminMenu[84][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[84][MN_URL]		= "./?menuType=weblog&mode=orderDayStatics"; 
$aryMallAdminMenu[84][MN_USE]		= "Y"; 
$aryMallAdminMenu[84][MN_ORDER]	= "2"; 
$aryMallAdminMenu[85][MN_NO]		= "85"; 
$aryMallAdminMenu[85][MN_NAME_KR]	= "월별매출분석"; 
$aryMallAdminMenu[85][MN_NAME_US]	= "Monthly Sales Statistics"; 
$aryMallAdminMenu[85][MN_NAME_CN]	= "月销售量分析"; 
$aryMallAdminMenu[85][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[85][MN_URL]		= "./?menuType=weblog&mode=orderMonthStatics"; 
$aryMallAdminMenu[85][MN_USE]		= "Y"; 
$aryMallAdminMenu[85][MN_ORDER]	= "3"; 
$aryMallAdminMenu[86][MN_NO]		= "86"; 
$aryMallAdminMenu[86][MN_NAME_KR]	= "분기별 매출통계"; 
$aryMallAdminMenu[86][MN_NAME_US]	= "Quarterly Sales Statistics"; 
$aryMallAdminMenu[86][MN_NAME_CN]	= "분기별 매출통계"; 
$aryMallAdminMenu[86][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[86][MN_URL]		= "./?menuType=weblog&mode=orderQuarterStatics"; 
$aryMallAdminMenu[86][MN_USE]		= "Y"; 
$aryMallAdminMenu[86][MN_ORDER]	= "4"; 
$aryMallAdminMenu[87][MN_NO]		= "87"; 
$aryMallAdminMenu[87][MN_NAME_KR]	= "상품분석"; 
$aryMallAdminMenu[87][MN_NAME_US]	= "Product Analysis"; 
$aryMallAdminMenu[87][MN_NAME_CN]	= "상품분석"; 
$aryMallAdminMenu[87][MN_LEVEL]	= "2"; 
$aryMallAdminMenu[87][MN_URL]		= "./?menuType=weblog&mode=orderProdCateStatics"; 
$aryMallAdminMenu[87][MN_USE]		= "Y"; 
$aryMallAdminMenu[87][MN_ORDER]	= "3"; 
$aryMallAdminMenu[88][MN_NO]		= "88"; 
$aryMallAdminMenu[88][MN_NAME_KR]	= "카테고리분석"; 
$aryMallAdminMenu[88][MN_NAME_US]	= "Category Analysis"; 
$aryMallAdminMenu[88][MN_NAME_CN]	= "카테고리분석"; 
$aryMallAdminMenu[88][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[88][MN_URL]		= "./?menuType=weblog&mode=orderProdCateStatics"; 
$aryMallAdminMenu[88][MN_USE]		= "Y"; 
$aryMallAdminMenu[88][MN_ORDER]	= "1"; 
$aryMallAdminMenu[89][MN_NO]		= "89"; 
$aryMallAdminMenu[89][MN_NAME_KR]	= "판매순위 분석"; 
$aryMallAdminMenu[89][MN_NAME_US]	= "Sales Ranking Analysis"; 
$aryMallAdminMenu[89][MN_NAME_CN]	= "판매순위 분석"; 
$aryMallAdminMenu[89][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[89][MN_URL]		= "./?menuType=weblog&mode=orderProdStatics"; 
$aryMallAdminMenu[89][MN_USE]		= "Y"; 
$aryMallAdminMenu[89][MN_ORDER]	= "2"; 
$aryMallAdminMenu[90][MN_NO]		= "90"; 
$aryMallAdminMenu[90][MN_NAME_KR]	= "장바구니 분석"; 
$aryMallAdminMenu[90][MN_NAME_US]	= "Shopping Bag Analysis"; 
$aryMallAdminMenu[90][MN_NAME_CN]	= "장바구니 분석"; 
$aryMallAdminMenu[90][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[90][MN_URL]		= "./?menuType=weblog&mode=prodBasketStatics"; 
$aryMallAdminMenu[90][MN_USE]		= "Y"; 
$aryMallAdminMenu[90][MN_ORDER]	= "3"; 
$aryMallAdminMenu[91][MN_NO]		= "91"; 
$aryMallAdminMenu[91][MN_NAME_KR]	= "상품보관함 분석"; 
$aryMallAdminMenu[91][MN_NAME_US]	= "Wish List Analysis"; 
$aryMallAdminMenu[91][MN_NAME_CN]	= "상품보관함 분석"; 
$aryMallAdminMenu[91][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[91][MN_URL]		= "./?menuType=weblog&mode=prodWishStatics"; 
$aryMallAdminMenu[91][MN_USE]		= "Y"; 
$aryMallAdminMenu[91][MN_ORDER]	= "4"; 
$aryMallAdminMenu[92][MN_NO]		= "92"; 
$aryMallAdminMenu[92][MN_NAME_KR]	= "주문분석"; 
$aryMallAdminMenu[92][MN_NAME_US]	= "Order Analysis"; 
$aryMallAdminMenu[92][MN_NAME_CN]	= "订单分析";  
$aryMallAdminMenu[92][MN_LEVEL]	= "2"; 
$aryMallAdminMenu[92][MN_URL]		= "./?menuType=weblog&mode=orderDayStatics2"; 
$aryMallAdminMenu[92][MN_USE]		= "Y"; 
$aryMallAdminMenu[92][MN_ORDER]	= "4"; 
$aryMallAdminMenu[93][MN_NO]		= "93"; 
$aryMallAdminMenu[93][MN_NAME_KR]	= "일별 주문통계"; 
$aryMallAdminMenu[93][MN_NAME_US]	= "Daily Order Statistics"; 
$aryMallAdminMenu[93][MN_NAME_CN]	= "日订单分析"; 
$aryMallAdminMenu[93][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[93][MN_URL]		= "./?menuType=weblog&mode=orderDayStatics2"; 
$aryMallAdminMenu[93][MN_USE]		= "Y"; 
$aryMallAdminMenu[93][MN_ORDER]	= "1"; 
$aryMallAdminMenu[94][MN_NO]		= "94"; 
$aryMallAdminMenu[94][MN_NAME_KR]	= "월별 주문통계"; 
$aryMallAdminMenu[94][MN_NAME_US]	= "Monthly Order Analysis"; 
$aryMallAdminMenu[94][MN_NAME_CN]	= "月订单分析";  
$aryMallAdminMenu[94][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[94][MN_URL]		= "./?menuType=weblog&mode=orderMonthStatics2"; 
$aryMallAdminMenu[94][MN_USE]		= "Y"; 
$aryMallAdminMenu[94][MN_ORDER]	= "2"; 
$aryMallAdminMenu[95][MN_NO]		= "95"; 
$aryMallAdminMenu[95][MN_NAME_KR]	= "상품별 주문통계"; 
$aryMallAdminMenu[95][MN_NAME_US]	= "Order Analysis by Product"; 
$aryMallAdminMenu[95][MN_NAME_CN]	= "商品类订单统计"; 
$aryMallAdminMenu[95][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[95][MN_URL]		= "./?menuType=weblog&mode=orderProdStatusStatics"; 
$aryMallAdminMenu[95][MN_USE]		= "Y"; 
$aryMallAdminMenu[95][MN_ORDER]	= "3"; 
$aryMallAdminMenu[96][MN_NO]		= "96"; 
$aryMallAdminMenu[96][MN_NAME_KR]	= "연령별 주문분석"; 
$aryMallAdminMenu[96][MN_NAME_US]	= "Order Statistics by Age"; 
$aryMallAdminMenu[96][MN_NAME_CN]	= "연령별 주문분석"; 
$aryMallAdminMenu[96][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[96][MN_URL]		= "./?menuType=weblog&mode=orderAgeStatics"; 
$aryMallAdminMenu[96][MN_USE]		= "Y"; 
$aryMallAdminMenu[96][MN_ORDER]	= "4"; 
$aryMallAdminMenu[97][MN_NO]		= "97"; 
$aryMallAdminMenu[97][MN_NAME_KR]	= "지역별 주문분석"; 
$aryMallAdminMenu[97][MN_NAME_US]	= "Order Statistics by Region"; 
$aryMallAdminMenu[97][MN_NAME_CN]	= "지역별 주문분석";  
$aryMallAdminMenu[97][MN_LEVEL]	= "3"; 
$aryMallAdminMenu[97][MN_URL]		= "./?menuType=weblog&mode=orderAreaStatics"; 
$aryMallAdminMenu[97][MN_USE]		= "Y"; 
$aryMallAdminMenu[97][MN_ORDER]	= "5"; 

$aryMallAdminLMenu[5][MN_NO]			= "6"; 
$aryMallAdminLMenu[5][MN_NAME_KR]	= "커뮤니티관리"; 
$aryMallAdminLMenu[5][MN_NAME_US]	= "Community Management"; 
$aryMallAdminLMenu[5][MN_NAME_CN]	= "交流管理"; 
$aryMallAdminLMenu[5][MN_URL]		= "./?menuType=community&mode=boardList"; 
$aryMallAdminLMenu[5][MN_USE]		= "Y"; 
$aryMallAdminLMenu[5][MN_ORDER]		= "7"; 
$aryMallAdminLMenu[5][MN_CODE]		= "006"; 
$aryMallAdminLMenu[5][MN_HIGH_01]	= ""; 
$aryMallAdminLMenu[5][MN_HIGH_02]	= ""; 
$aryMallAdminMenu[6][MN_NO]		= "6"; 
$aryMallAdminMenu[6][MN_NAME_KR]	= "커뮤니티관리"; 
$aryMallAdminMenu[6][MN_NAME_US]	= "Community Management"; 
$aryMallAdminMenu[6][MN_NAME_CN]	= "커뮤니티관리"; 
$aryMallAdminMenu[6][MN_LEVEL]	= "1"; 
$aryMallAdminMenu[6][MN_URL]		= "./?menuType=community&mode=boardList"; 
$aryMallAdminMenu[6][MN_USE]		= "Y"; 
$aryMallAdminMenu[6][MN_ORDER]	= "7"; 
?>
