<div id="contentArea">
	<div class="contentTop">
		<h2>월별 매출분석</h2>
	</div>

	<!-- ******** 컨텐츠 ********* -->
	<div class="logGraphWrap mt30" style="height:70px;">
		<?include MALL_WEB_PATH."shopAdmin/weblog/bar_chart.inc.php";?>
	</div>
	<!-- 그래프 -->

	<div class="tableList mt30">
		<table>
			<colgroup>
				<col style="width:20%;"/>				
				<col style="width:20%;"/>
				<col style="width:20%;background-color:#f1f7f9" />
				<col style="width:20%;"/>
				<col style="width:20%;"/>
			</colgroup>
			<tr>
				<th>시간</th>
				<th>전일</th>
				<th>해당일</th>
				<th>1주전</th>
				<th>한달평균</th>
			</tr>			
			<tr>
				<td>0</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>	
			<tr>
				<td>1</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>2</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>3</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>4</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>5</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>6</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>7</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>8</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>9</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>10</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>11</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>12</td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>13</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>14</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>15</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>16</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>17</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>18</td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>19</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>20</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>21</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>22</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td>23</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
		</table>
	</div>
</div>
<!-- ******** 컨텐츠 ********* -->