<?
$SHOP_ARY_DELIVERY['SHOP_DELIVERY_ST'] = "S"; 
$SHOP_ARY_DELIVERY['SHOP_DELIVERY_ST_PRICE'] = "40000"; 
$SHOP_ARY_DELIVERY['SHOP_DELIVERY_PRICE'] = "3000";
$SHOP_ARY_DELIVERY['SHOP_DELIVERY_EXP_PRICE'] = "";
$SHOP_ARY_DELIVERY['SHOP_DELIVERY_EXP_AREA'] = "";
$SHOP_PAY_PG = "K";
$SHOP_SITE_CODE = "V2736";
$SHOP_SITE_KEY  = "2ciEFnPvUamDlW0tGTxH.KT__";
$SHOP_ARY_DELIVERY['SHOP_DELIVERY_ST_FOR_PRICE'] = "9999999999"; 
$SHOP_ARY_DELIVERY['SHOP_DELIVERY_FOR_PRICE'] = "10000";
$SHOP_PAY_FOR_PG = "/X/R/B";
?>
